-- Generated by tools/build_icon_sheets.py; do not edit by hand.
-- Geometry of the paged icon sprite sheets (assets/icons/<Style>/<page>.png),
-- every icon name's cell (0-based across pages: page = cell // PerPage) and,
-- for names Google's Material Icons fonts have, their codepoint there.
local IconSheet = {
	Version = 2, -- layout version; part of cached file names
	Cell = 64, -- icon size in px
	Pitch = 72, -- distance between cells (cell + gutters)
	Gutter = 4,
	Columns = 14,
	Rows = 14, -- per full page
	PerPage = 196,
	Pages = 23,
	Count = 4314, -- distinct glyphs
	Index = {}, -- name -> cell
	Codepoints = {}, -- name -> Material Icons font codepoint
}

-- One icon per line: name, cell, then its Material Icons codepoint (hex)
-- unless it is a Material Symbols-only icon.
local DATA = [[
10k 139 e951
10mp 140 e952
11mp 141 e953
123 142 eb8d
12mp 143 e954
13mp 144 e955
14mp 145 e956
15mp 146 e957
16mp 147 e958
17mp 148 e959
18_up_rating 149 f8fd
18mp 150 e95a
19mp 151 e95b
1k 152 e95c
1k_plus 153 e95d
1x_mobiledata 154 efcd
1x_mobiledata_badge 2189
20mp 155 e95e
21mp 156 e95f
22mp 157 e960
23mp 158 e961
24fps_select 2190
24mp 159 e962
2d 2191
2d_2 2192
2k 160 e963
2k_plus 161 e964
2mp 162 e965
30fps 163 efce
30fps_select 164 efcf
360 165 e577
3d 2193
3d_2 2194
3d_rotation 166 e84d
3g_mobiledata 167 efd0
3g_mobiledata_badge 2195
3k 168 e966
3k_plus 169 e967
3mp 170 e968
3p 171 efd1
4g_mobiledata 172 efd2
4g_mobiledata_badge 2196
4g_plus_mobiledata 173 efd3
4k 174 e072
4k_plus 175 e969
4mp 176 e96a
50mp 2197
5g 177 ef38
5g_mobiledata_badge 2198
5k 178 e96b
5k_plus 179 e96c
5mp 180 e96d
60fps 181 efd4
60fps_select 182 efd5
6_ft_apart 183 f21e
6k 184 e96e
6k_plus 185 e96f
6mp 186 e970
7k 187 e971
7k_plus 188 e972
7mp 189 e973
8k 190 e974
8k_plus 191 e975
8mp 192 e976
9k 193 e977
9k_plus 194 e978
9mp 195 e979
abc 196 eb94
ac_unit 197 eb3b
access_alarm 198 e190
access_alarms 199 e191
access_time 200 e192
access_time_filled 201 efd6
accessibility 202 e84e
accessibility_new 203 e92c
accessible 204 e914
accessible_forward 205 e934
accessible_menu 2199
account_balance 206 e84f
account_balance_wallet 207 e850
account_box 208 e851
account_child 2200
account_child_invert 2201
account_circle 209 e853
account_circle_filled 2202
account_circle_off 2203
account_tree 210 e97a
action_key 2204
activity_zone 2205
acupuncture 2206
acute 2207
ad 2208
ad_group 2209
ad_group_off 2210
ad_off 2211
ad_units 211 ef39
adaptive_audio_mic 2212
adaptive_audio_mic_off 2213
adb 212 e60e
add 0 e145
add_2 2214
add_a_photo 213 e439
add_ad 2215
add_alarm 214 e193
add_alert 215 e003
add_box 216 e146
add_business 217 e729
add_call 218 e0e8
add_card 219 eb86
add_chart 220 e97b
add_circle 221 e147
add_circle_outline 222 e148
add_column_left 2216
add_column_right 2217
add_comment 223 e266
add_diamond 2218
add_home 224 f8eb
add_home_work 225 f8ed
add_ic_call 226 e97c
add_link 227 e178
add_location 228 e567
add_location_alt 229 ef3a
add_moderator 230 e97d
add_notes 2219
add_photo_alternate 231 e43e
add_reaction 232 e1d3
add_road 233 ef3b
add_row_above 2220
add_row_below 2221
add_shopping_cart 234 e854
add_task 235 f23a
add_to_drive 236 e65c
add_to_home_screen 237 e1fe
add_to_photos 238 e39d
add_to_queue 239 e05c
add_triangle 2222
addchart 240 ef3c
adf_scanner 241 eada
adjust 242 e39e
admin_meds 2223
admin_panel_settings 243 ef3d
adobe 244 ea96
ads_click 245 e762
agender 2224
agriculture 246 ea79
air 247 efd8
air_freshener 2225
air_purifier 2226
air_purifier_gen 2227
airline_seat_flat 248 e630
airline_seat_flat_angled 249 e631
airline_seat_individual_suite 250 e632
airline_seat_legroom_extra 251 e633
airline_seat_legroom_normal 252 e634
airline_seat_legroom_reduced 253 e635
airline_seat_recline_extra 254 e636
airline_seat_recline_normal 255 e637
airline_stops 256 e7d0
airlines 257 e7ca
airplane_ticket 258 efd9
airplanemode_active 259 e195
airplanemode_inactive 260 e194
airplanemode_off 260 e194
airplanemode_on 259 e195
airplay 261 e055
airport_shuttle 262 eb3c
airware 2228
airwave 2228
alarm 1 e855
alarm_add 263 e856
alarm_off 264 e857
alarm_on 265 e858
alarm_pause 2229
alarm_smart_wake 2230
album 266 e019
align_center 2231
align_end 2232
align_flex_center 2233
align_flex_end 2234
align_flex_start 2235
align_horizontal_center 267 e00f
align_horizontal_left 268 e00d
align_horizontal_right 269 e010
align_items_stretch 2236
align_justify_center 2237
align_justify_flex_end 2238
align_justify_flex_start 2239
align_justify_space_around 2240
align_justify_space_between 2241
align_justify_space_even 2242
align_justify_stretch 2243
align_self_stretch 2244
align_space_around 2245
align_space_between 2246
align_space_even 2247
align_start 2248
align_stretch 2249
align_vertical_bottom 270 e015
align_vertical_center 271 e011
align_vertical_top 272 e00c
all_inbox 273 e97f
all_inclusive 274 eb3d
all_match 2250
all_out 275 e90b
allergies 2251
allergy 2252
alt_route 276 f184
alternate_email 277 e0e6
altitude 2253
ambient_screen 2254
ambulance 2255
amend 2256
amp_stories 278 ea13
analytics 279 ef3e
anchor 280 f1cd
android 281 e859
android_cell_4_bar 2257
android_cell_4_bar_alert 2258
android_cell_4_bar_off 2259
android_cell_4_bar_plus 2260
android_cell_5_bar 2261
android_cell_5_bar_alert 2262
android_cell_5_bar_off 2263
android_cell_5_bar_plus 2264
android_cell_dual_4_bar 2265
android_cell_dual_4_bar_alert 2266
android_cell_dual_4_bar_plus 2267
android_cell_dual_5_bar 2268
android_cell_dual_5_bar_alert 2269
android_cell_dual_5_bar_plus 2270
android_wifi_3_bar 2271
android_wifi_3_bar_alert 2272
android_wifi_3_bar_lock 2273
android_wifi_3_bar_off 2274
android_wifi_3_bar_plus 2275
android_wifi_3_bar_question 2276
android_wifi_4_bar 2277
android_wifi_4_bar_alert 2278
android_wifi_4_bar_lock 2279
android_wifi_4_bar_off 2280
android_wifi_4_bar_plus 2281
android_wifi_4_bar_question 2282
animated_images 2283
animation 282 e71c
announcement 283 e85a
antigravity 2284
aod 284 efda
aod_tablet 2285
aod_watch 2286
apartment 285 ea40
api 286 f1b7
apk_document 2287
apk_install 2288
app_badging 2289
app_blocking 287 ef3f
app_promo 2290
app_registration 288 ef40
app_settings_alt 289 ef41
app_shortcut 290 eae4
apparel 2291
apple 291 ea80
approval 292 e982
approval_delegation 2292
approval_delegation_off 2293
apps 293 e5c3
apps_outage 294 e7cc
apps_plus 2294
aq 2295
aq_indoor 2296
ar_on_you 2297
ar_stickers 2298
architecture 295 ea3b
archive 296 e149
area_chart 297 e770
arming_countdown 2299
arrow_and_edge 2300
arrow_back 2 e5c4
arrow_back_2 2301
arrow_back_ios 298 e5e0
arrow_back_ios_new 299 e2ea
arrow_circle_down 300 f181
arrow_circle_left 301 eaa7
arrow_circle_right 302 eaaa
arrow_circle_up 303 f182
arrow_cool_down 2302
arrow_downward 304 e5db
arrow_downward_alt 2303
arrow_drop_down 3 e5c5
arrow_drop_down_circle 305 e5c6
arrow_drop_up 4 e5c7
arrow_forward 5 e5c8
arrow_forward_ios 306 e5e1
arrow_insert 2304
arrow_left 307 e5de
arrow_left_alt 2305
arrow_menu_close 2306
arrow_menu_open 2307
arrow_or_edge 2308
arrow_outward 308 f8ce
arrow_range 2309
arrow_right 309 e5df
arrow_right_alt 310 e941
arrow_selector_tool 2310
arrow_shape_up 2311
arrow_shape_up_stack 2312
arrow_shape_up_stack_2 2313
arrow_split 2314
arrow_top_left 2315
arrow_top_right 2316
arrow_upload_progress 2317
arrow_upload_ready 2318
arrow_upward 311 e5d8
arrow_upward_alt 2319
arrow_warm_up 2320
arrows_input 2321
arrows_left_right_circle 2322
arrows_more_down 2323
arrows_more_up 2324
arrows_output 2325
arrows_outward 2326
arrows_up_down_circle 2327
art_track 312 e060
article 313 ef42
article_person 2328
article_shortcut 2329
artist 2330
aspect_ratio 314 e85b
assessment 315 e85c
assignment 316 e85d
assignment_add 317 f848
assignment_globe 2331
assignment_ind 318 e85e
assignment_late 319 e85f
assignment_return 320 e860
assignment_returned 321 e861
assignment_turned_in 322 e862
assist_walker 323 f8d5
assistant 324 e39f
assistant_device 2332
assistant_direction 325 e988
assistant_navigation 326 e989
assistant_on_hub 2333
assistant_photo 327 e3a0
assured_workload 328 eb6f
asterisk 2334
astrophotography_auto 2335
astrophotography_off 2336
atm 329 e573
atr 2337
attach_email 330 ea5e
attach_file 6 e226
attach_file_add 2338
attach_file_off 2339
attach_money 331 e227
attachment 332 e2bc
attractions 333 ea52
attribution 334 efdb
audio_capture 2340
audio_description 2341
audio_file 335 eb82
audio_video_receiver 2342
audiotrack 336 e3a1
auto_activity_zone 2343
auto_awesome 7 e65f
auto_awesome_mosaic 337 e660
auto_awesome_motion 338 e661
auto_delete 339 ea4c
auto_detect_voice 2344
auto_draw_solid 2345
auto_fix 2346
auto_fix_high 340 e663
auto_fix_normal 341 e664
auto_fix_off 342 e665
auto_graph 343 e4fb
auto_label 2347
auto_meeting_room 2348
auto_mode 344 ec20
auto_read_pause 2349
auto_read_play 2350
auto_schedule 2351
auto_stories 345 e666
auto_stories_off 2352
auto_timer 2353
auto_towing 2354
auto_transmission 2355
auto_videocam 2356
autofps_select 346 efdc
automation 2357
autopause 2358
autopay 2359
autoplay 2360
autorenew 8 e863
autostop 2361
av1 2362
av_timer 347 e01b
avc 2363
avg_pace 2364
avg_time 2365
avocado_bean 2366
award_meal 2367
award_star 2368
azm 2369
b_circle 2370
baby_changing_station 348 f19b
back_hand 349 e764
back_to_tab 2371
background_dot_large 2372
background_dot_small 2373
background_grid_small 2374
background_replace 2375
backlight_high 2376
backlight_high_off 2377
backlight_low 2378
backpack 9 f19c
backspace 350 e14a
backup 351 e864
backup_table 352 ef43
badge 353 ea67
badge_critical_battery 2379
badminton 2380
bakery_dining 354 ea53
balance 355 eaf6
balcony 356 e58f
ballot 357 e172
bar_chart 10 e26b
bar_chart_4_bars 2381
bar_chart_off 2382
barcode 2383
barcode_reader 358 f85c
barcode_scanner 2384
barefoot 2385
batch_prediction 359 f0f5
bath_bedrock 2386
bath_outdoor 2387
bath_private 2388
bath_public_large 2389
bath_soak 2390
bathroom 360 efdd
bathtub 361 ea41
battery_0_bar 362 ebdc
battery_1_bar 363 ebd9
battery_20 2391
battery_2_bar 364 ebe0
battery_30 2392
battery_3_bar 365 ebdd
battery_4_bar 366 ebe2
battery_50 2393
battery_5_bar 367 ebd4
battery_60 2394
battery_6_bar 368 ebd2
battery_80 2395
battery_90 2396
battery_alert 369 e19c
battery_android_0 2397
battery_android_1 2398
battery_android_2 2399
battery_android_3 2400
battery_android_4 2401
battery_android_5 2402
battery_android_6 2403
battery_android_alert 2404
battery_android_bolt 2405
battery_android_frame_1 2406
battery_android_frame_2 2407
battery_android_frame_3 2408
battery_android_frame_4 2409
battery_android_frame_5 2410
battery_android_frame_6 2411
battery_android_frame_alert 2412
battery_android_frame_bolt 2413
battery_android_frame_full 2414
battery_android_frame_plus 2415
battery_android_frame_question 2416
battery_android_frame_share 2417
battery_android_frame_shield 2418
battery_android_full 2419
battery_android_plus 2420
battery_android_question 2421
battery_android_share 2422
battery_android_shield 2423
battery_change 2424
battery_charging_20 2425
battery_charging_20_2 2426
battery_charging_30 2427
battery_charging_30_2 2428
battery_charging_50 2429
battery_charging_50_2 2430
battery_charging_60 2431
battery_charging_60_2 2432
battery_charging_80 2433
battery_charging_80_2 2434
battery_charging_90 2435
battery_charging_full 370 e1a3
battery_charging_full_2 2436
battery_error 2437
battery_full 371 e1a4
battery_full_alt 2438
battery_horiz_000 2439
battery_horiz_050 2440
battery_horiz_075 2441
battery_low 2442
battery_plus 2443
battery_profile 2444
battery_saver 372 efde
battery_share 2445
battery_status_good 2446
battery_std 373 e1a5
battery_unknown 374 e1a6
battery_vert_005 2447
battery_vert_020 2448
battery_vert_050 2449
battery_very_low 2379
beach_access 375 eb3e
bed 376 efdf
bedroom_baby 377 efe0
bedroom_child 378 efe1
bedroom_parent 379 efe2
bedtime 380 ef44
bedtime_off 381 eb76
beenhere 382 e52d
beer_meal 2450
bento 383 f1f4
bia 2451
bid_landscape 2452
bid_landscape_disabled 2453
bigtop_updates 2454
bike_dock 2455
bike_lane 2456
bike_scooter 384 ef45
biotech 385 ea3a
blanket 2457
blender 386 efe3
blind 387 f8d6
blinds 388 e286
blinds_2 2458
blinds_2_closed 2459
blinds_closed 389 ec1f
block 11 e14b
block_flipped 390 ef46
blood_pressure 2460
bloodtype 391 efe4
bluetooth 392 e1a7
bluetooth_audio 393 e60f
bluetooth_connected 394 e1a8
bluetooth_disabled 395 e1a9
bluetooth_drive 396 efe5
bluetooth_searching 397 e1aa
blur_circular 398 e3a2
blur_linear 399 e3a3
blur_medium 2461
blur_off 400 e3a4
blur_on 401 e3a5
blur_short 2462
boat_bus 2463
boat_railway 2464
body_fat 2465
body_system 2466
bolt 12 ea0b
bolt_boost 2467
bomb 2468
book 402 e865
book_2 2469
book_3 2470
book_4 2471
book_5 2472
book_6 2473
book_online 403 f217
book_ribbon 2474
bookmark 13 e866
bookmark_add 404 e598
bookmark_added 405 e599
bookmark_bag 2475
bookmark_border 14 e867
bookmark_check 2476
bookmark_flag 2477
bookmark_heart 2478
bookmark_manager 2479
bookmark_outline 14 e867
bookmark_remove 406 e59a
bookmark_stacks 2480
bookmark_star 2481
bookmarks 407 e98b
books_movies_and_music 2482
border_all 408 e228
border_bottom 409 e229
border_clear 410 e22a
border_color 411 e22b
border_horizontal 412 e22c
border_inner 413 e22d
border_left 414 e22e
border_outer 415 e22f
border_right 416 e230
border_style 417 e231
border_top 418 e232
border_vertical 419 e233
borg 2483
bottom_app_bar 2484
bottom_drawer 2485
bottom_navigation 2486
bottom_panel_close 2487
bottom_panel_open 2488
bottom_right_click 2489
bottom_sheets 2490
box 2491
box_add 2492
box_edit 2493
boy 420 eb67
brand_awareness 2494
brand_family 2495
branding_watermark 421 e06b
breakfast_dining 422 ea54
breaking_news 2496
breaking_news_alt_1 2497
breastfeeding 2498
brick 2499
briefcase_meal 2500
brightness_1 423 e3a6
brightness_2 424 e3a7
brightness_3 425 e3a8
brightness_4 15 e3a9
brightness_5 426 e3aa
brightness_6 427 e3ab
brightness_7 16 e3ac
brightness_alert 2501
brightness_auto 428 e1ab
brightness_dark 15 e3a9
brightness_empty 2502
brightness_high 429 e1ac
brightness_light 16 e3ac
brightness_low 430 e1ad
brightness_medium 431 e1ae
bring_your_own_ip 2503
broadcast_on_home 432 f8f8
broadcast_on_personal 433 f8f9
broken_image 434 e3ad
browse 2504
browse_activity 2505
browse_gallery 435 ebd1
browser_not_supported 436 ef47
browser_updated 437 e7cf
brunch_dining 438 ea73
brush 439 e3ae
bubble 2506
bubble_chart 440 e6dd
bubbles 2507
bucket_check 2508
bug_report 441 e868
build 17 e869
build_circle 442 ef48
bullet_chart 2509
bungalow 443 e591
burst_mode 444 e43c
bus_alert 445 e98f
bus_map_pin 2510
bus_railway 2511
business 446 e0af
business_center 447 eb3f
business_chip 2512
business_messages 2513
buttons_alt 2514
cabin 448 e589
cable 449 efe6
cable_car 2515
cached 450 e86a
cadence 2516
cake 451 e7e9
cake_add 2517
calculate 452 ea5f
calendar_add_on 2518
calendar_apps_script 2519
calendar_check 2520
calendar_clock 2521
calendar_lock 2522
calendar_meal 2523
calendar_meal_2 2524
calendar_month 453 ebcc
calendar_today 18 e935
calendar_view_day 454 e936
calendar_view_month 455 efe7
calendar_view_week 456 efe8
call 457 e0b0
call_end 458 e0b1
call_end_alt 2525
call_log 2526
call_made 459 e0b2
call_merge 460 e0b3
call_missed 461 e0b4
call_missed_outgoing 462 e0e4
call_quality 2527
call_received 463 e0b5
call_split 464 e0b6
call_to_action 465 e06c
camera 466 e3af
camera_alt 19 e3b0
camera_enhance 467 e8fc
camera_front 468 e3b1
camera_indoor 469 efe9
camera_outdoor 470 efea
camera_rear 471 e3b2
camera_roll 472 e3b3
camera_video 2528
cameraswitch 473 efeb
campaign 474 ef49
camping 2529
cancel 20 e5c9
cancel_presentation 475 e0e9
cancel_schedule_send 476 ea39
candle 2530
candlestick_chart 477 ead4
cannabis 2531
captive_portal 2532
capture 2533
car_crash 478 ebf2
car_defrost_left 2534
car_defrost_low_left 2535
car_defrost_low_right 2536
car_defrost_mid_left 2537
car_defrost_mid_low_left 2538
car_defrost_mid_low_right 2539
car_defrost_mid_right 2540
car_defrost_right 2541
car_fan_low_left 2542
car_fan_low_mid_left 2543
car_fan_low_right 2544
car_fan_mid_left 2545
car_fan_mid_low_right 2546
car_fan_mid_right 2547
car_fan_recirculate 2548
car_fan_recirculate_2 2549
car_gear 2550
car_lock 2551
car_mirror_heat 2552
car_rental 479 ea55
car_repair 480 ea56
car_seat_off 2553
car_tag 2554
card_giftcard 481 e8f6
card_membership 482 e8f7
card_travel 483 e8f8
cardio_load 2555
cardiology 2556
cards 2557
cards_stack 2558
cards_star 2559
carpenter 484 f1f8
carry_on_bag 2560
carry_on_bag_checked 2561
carry_on_bag_inactive 2562
carry_on_bag_question 2563
cases 485 e992
casino 486 eb40
cast 487 e307
cast_connected 488 e308
cast_for_education 489 efec
cast_pause 2564
cast_warning 2565
castle 490 eab1
catching_pokemon 491 e508
category 492 e574
category_search 2566
celebration 493 ea65
cell_merge 2567
cell_tower 494 ebba
cell_wifi 495 e0ec
center_focus_strong 496 e3b4
center_focus_weak 497 e3b5
chair 498 efed
chair_alt 499 efee
chair_counter 2568
chair_fireplace 2569
chair_umbrella 2570
chalet 500 e585
change_circle 501 e2e7
change_history 502 e86b
charger 2571
charging_station 503 f19d
chart_data 2572
chat 21 e0b7
chat_add_on 2573
chat_apps_script 2574
chat_bubble 504 e0ca
chat_bubble_off 2575
chat_bubble_outline 505 e0cb
chat_dashed 2576
chat_display 2577
chat_error 2578
chat_info 2579
chat_paste_go 2580
chat_paste_go_2 2581
check 22 e5ca
check_alert 2582
check_box 23 e834
check_box_outline_blank 24 e835
check_circle 25 e86c
check_circle_filled 2583
check_circle_outline 506 e92d
check_circle_unread 2584
check_in_out 2585
check_indeterminate_small 2586
check_small 2587
checkbook 2588
checked_bag 2589
checked_bag_question 2590
checklist 507 e6b1
checklist_rtl 508 e6b3
checkroom 509 f19e
cheer 2591
chef_hat 2592
chess 2593
chess_bishop 2594
chess_bishop_2 2595
chess_king 2596
chess_king_2 2597
chess_knight 2598
chess_pawn 2599
chess_pawn_2 2600
chess_queen 2601
chess_rook 2602
chevron_backward 2603
chevron_forward 2604
chevron_left 26 e5cb
chevron_line_up 2605
chevron_right 27 e5cc
child_care 510 eb41
child_friendly 511 eb42
child_hat 2606
chip_extraction 2607
chips 2608
chrome_reader_mode 512 e86d
chromecast_2 2609
chromecast_device 2610
chronic 2611
church 513 eaae
cinematic_blur 2612
circle 514 ef4a
circle_circle 2613
circle_notifications 515 e994
circles 2614
circles_ext 2615
clarify 2616
class 516 e86e
clean_hands 517 f21f
cleaning 2617
cleaning_bucket 2618
cleaning_services 518 f0ff
clear 519 e14c
clear_all 520 e0b8
clear_day 2619
clear_night 2620
climate_mini_split 2621
clinical_notes 2622
clock_arrow_down 2623
clock_arrow_up 2624
clock_loader_10 2625
clock_loader_20 2626
clock_loader_40 2627
clock_loader_60 2628
clock_loader_80 2629
clock_loader_90 2630
close 28 e5cd
close_fullscreen 29 f1cf
close_small 2631
closed_caption 521 e01c
closed_caption_add 2632
closed_caption_disabled 522 f1dc
closed_caption_display 2633
closed_caption_off 523 e996
cloud 30 e2bd
cloud_alert 2634
cloud_circle 524 e2be
cloud_done 525 e2bf
cloud_download 526 e2c0
cloud_lock 2635
cloud_off 527 e2c1
cloud_queue 528 e2c2
cloud_sync 529 eb5a
cloud_upload 530 e2c3
cloudy 2636
cloudy_filled 2636
cloudy_snowing 531 e810
co2 532 e7b0
co_present 533 eaf0
code 31 e86f
code_blocks 2637
code_off 534 e4f3
code_xml 2638
coffee 535 efef
coffee_maker 536 eff0
cognition 2639
cognition_2 2640
collapse_all 2641
collapse_content 2642
collections 537 e3b6
collections_bookmark 538 e431
color_lens 539 e3b7
colorize 32 e3b8
colors 2643
combine_columns 2644
comedy_mask 2645
comic_bubble 2646
comment 33 e0b9
comment_bank 540 ea4e
comments_disabled 541 e7a2
commit 542 eaf5
communication 2647
communities 2648
communities_filled 2648
commute 543 e940
compare 544 e3b9
compare_arrows 545 e915
compass_calibration 546 e57c
component_exchange 2649
compost 547 e761
compress 548 e94d
computer 549 e30a
computer_arrow_up 2650
computer_cancel 2651
computer_sound 2652
concierge 2653
conditions 2654
confirmation_num 550 e638
confirmation_number 550 e638
congenital 2655
connect_without_contact 551 f223
connected_tv 552 e998
connecting_airports 553 e7c9
construction 554 ea3c
contact_emergency 555 f8d1
contact_mail 556 e0d0
contact_page 557 f22e
contact_phone 558 e0cf
contact_phone_filled 2656
contact_support 559 e94c
contactless 560 ea71
contactless_off 2657
contacts 561 e0ba
contacts_product 2658
content_copy 34 e14d
content_cut 562 e14e
content_paste 563 e14f
content_paste_go 564 ea8e
content_paste_off 565 e4f8
content_paste_search 566 ea9b
contextual_token 2659
contextual_token_add 2660
contract 2661
contract_delete 2662
contract_edit 2663
contrast 567 eb37
contrast_circle 2664
contrast_rtl_off 2665
contrast_square 2666
control_camera 568 e074
control_point 569 e3ba
control_point_duplicate 570 e3bb
controller_gen 2667
conversation 2668
conversion_path 2669
conversion_path_off 2670
convert_to_text 2671
conveyor_belt 571 f867
cookie 572 eaac
cookie_off 2672
cooking 2673
cool_to_dry 2674
copy_all 573 e2ec
copyright 574 e90c
coronavirus 575 f221
corporate_fare 576 f1d0
cottage 577 e587
counter_0 2675
counter_1 2676
counter_2 2677
counter_3 2678
counter_4 2679
counter_5 2680
counter_6 2681
counter_7 2682
counter_8 2683
counter_9 2684
countertops 578 f1f7
create 579 e150
create_new_folder 580 e2cc
credit_card 35 e870
credit_card_clock 2685
credit_card_gear 2686
credit_card_heart 2687
credit_card_off 581 e4f4
credit_score 582 eff1
crib 583 e588
crisis_alert 584 ebe9
crop 585 e3be
crop_16_9 586 e3bc
crop_21_9 2688
crop_2_3 2689
crop_3_2 587 e3bd
crop_5_4 588 e3bf
crop_7_5 589 e3c0
crop_9_16 2690
crop_din 590 e3c1
crop_free 591 e3c2
crop_landscape 592 e3c3
crop_original 593 e3c4
crop_portrait 594 e3c5
crop_rotate 595 e437
crop_square 596 e3c6
crossword 2691
crowdsource 2692
crown 2693
cruelty_free 597 e799
css 598 eb93
csv 2694
currency_bitcoin 599 ebc5
currency_exchange 600 eb70
currency_franc 601 eafa
currency_lira 602 eaef
currency_pound 603 eaf1
currency_ruble 604 eaec
currency_rupee 605 eaf7
currency_rupee_circle 2695
currency_yen 606 eafb
currency_yuan 607 eaf9
curtains 608 ec1e
curtains_closed 609 ec1d
custom_typography 2696
cut 2697
cycle 2698
cyclone 610 ebd5
dangerous 611 e99a
dark_mode 36 e51c
dashboard 37 e871
dashboard_2 2699
dashboard_2_add 2700
dashboard_2_edit 2701
dashboard_2_gear 2702
dashboard_customize 612 e99b
data_alert 2703
data_array 613 ead1
data_check 2704
data_exploration 614 e76f
data_info_alert 2705
data_loss_prevention 2706
data_object 615 ead3
data_saver_off 616 eff2
data_saver_on 617 eff3
data_table 2707
data_thresholding 618 eb9f
data_usage 619 e1af
database 2708
database_off 2709
database_search 2710
database_upload 2711
dataset 620 f8ee
dataset_linked 621 f8ef
date_range 622 e916
deblur 623 eb77
deceased 2712
decimal_decrease 2713
decimal_increase 2714
deck 624 ea42
dehaze 625 e3c7
delete 38 e872
delete_forever 626 e92b
delete_history 2715
delete_outline 627 e92e
delete_sweep 628 e16c
delivery_dining 629 ea72
delivery_truck_bolt 2716
delivery_truck_speed 2717
demography 2718
density_large 630 eba9
density_medium 631 eb9e
density_small 632 eba8
dentistry 2719
departure_board 633 e576
deployed_code 2720
deployed_code_account 2721
deployed_code_alert 2722
deployed_code_history 2723
deployed_code_update 2724
dermatology 2725
description 634 e873
deselect 635 ebb6
design_services 636 f10a
desk 637 f8f4
deskphone 2726
desktop_access_disabled 638 e99d
desktop_cloud 2727
desktop_cloud_stack 2728
desktop_landscape 2729
desktop_landscape_add 2730
desktop_mac 639 e30b
desktop_portrait 2731
desktop_windows 640 e30c
destruction 2732
details 641 e3c8
detection_and_zone 2733
detection_and_zone_off 2734
detector 2735
detector_alarm 2736
detector_battery 2737
detector_co 2738
detector_offline 2739
detector_smoke 2740
detector_status 2741
developer_board 642 e30d
developer_board_off 643 e4ff
developer_guide 2742
developer_mode 644 e1b0
developer_mode_tv 2743
device_band 2744
device_hub 645 e335
device_reset 2745
device_swoosh_star 2746
device_thermostat 646 e1ff
device_unknown 647 e339
devices 648 e1b1
devices_fold 649 ebde
devices_fold_2 2747
devices_off 2748
devices_other 650 e337
devices_wearables 2749
dew_point 651 f879
diagnosis 2750
diagonal_line 2751
dialer_sip 652 e0bb
dialogs 2752
dialpad 653 e0bc
diamond 654 ead5
diamond_shine 2753
dictionary 2754
difference 655 eb7d
digital_out_of_home 2755
digital_wellbeing 2756
dine_heart 2757
dine_in 2758
dine_lamp 2759
dining 656 eff4
dinner_dining 657 ea57
directions 658 e52e
directions_alt 2760
directions_alt_off 2761
directions_bike 659 e52f
directions_boat 660 e532
directions_boat_filled 661 eff5
directions_bus 662 e530
directions_bus_filled 663 eff6
directions_car 664 e531
directions_car_filled 665 eff7
directions_ferry 660 e532
directions_off 666 f10f
directions_railway 667 e534
directions_railway_2 2762
directions_railway_filled 668 eff8
directions_run 669 e566
directions_subway 670 e533
directions_subway_filled 671 eff9
directions_train 667 e534
directions_transit 672 e535
directions_transit_filled 673 effa
directions_walk 674 e536
directory_sync 2763
dirty_lens 675 ef4b
disabled_by_default 676 f230
disabled_visible 677 e76e
disc_full 678 e610
discord 679 ea6c
discount 680 ebc9
discover_tune 2764
dishwasher 2765
dishwasher_gen 2766
display_add 2767
display_external_input 2768
display_group 2769
display_settings 681 eb97
distance 2770
diversity_1 682 f8d7
diversity_2 683 f8d8
diversity_3 684 f8d9
diversity_4 2771
dnd_forwardslash 685 e611
dns 686 e875
do_disturb 687 f08c
do_disturb_alt 688 f08d
do_disturb_off 689 f08e
do_disturb_on 690 f08f
do_not_disturb 691 e612
do_not_disturb_alt 685 e611
do_not_disturb_off 692 e643
do_not_disturb_on 693 e644
do_not_disturb_on_total_silence 694 effb
do_not_step 695 f19f
do_not_touch 696 f1b0
dock 697 e30e
dock_to_bottom 2772
dock_to_left 2773
dock_to_right 2774
docs 2775
docs_add_on 2776
docs_apps_script 2777
document_scanner 698 e5fa
document_search 2778
document_share 2779
domain 699 e7ee
domain_add 700 eb62
domain_disabled 701 e0ef
domain_disabled_check 2780
domain_verification 702 ef4c
domain_verification_off 2781
domino_mask 2782
done 39 e876
done_all 703 e877
done_outline 704 e92f
donut_large 705 e917
donut_small 706 e918
door_back 707 effc
door_front 708 effd
door_open 2783
door_sensor 2784
door_sliding 709 effe
doorbell 710 efff
doorbell_3p 2785
doorbell_chime 2786
double_arrow 711 ea50
downhill_skiing 712 e509
download 40 f090
download_2 2787
download_done 713 f091
download_for_offline 714 f000
downloading 715 f001
draft 2788
draft_orders 2789
drafts 716 e151
drag_click 2790
drag_handle 41 e25d
drag_indicator 42 e945
drag_pan 2791
draw 717 e746
draw_abstract 2792
draw_collage 2793
drawing_recognition 2794
dresser 2795
drive_eta 718 e613
drive_export 2796
drive_file_move 719 e675
drive_file_move_outline 720 e9a1
drive_file_move_rtl 721 e76d
drive_file_rename 2797
drive_file_rename_outline 722 e9a2
drive_folder_upload 723 e9a3
drone 2798
drone_2 2799
dropdown 2800
dropdown_menu 2801
dropper_eye 2802
dry 724 f1b3
dry_cleaning 725 ea58
dual_screen 2803
duo 726 e9a5
dvr 727 e1b2
dynamic_feed 728 ea14
dynamic_form 729 f1bf
e911_avatar 2804
e911_emergency 2805
e_mobiledata 730 f002
e_mobiledata_badge 2806
ear_sound 2807
earbud_case 2808
earbud_left 2809
earbud_right 2810
earbuds 731 f003
earbuds_2 2811
earbuds_battery 732 f004
early_on 2812
earthquake 2813
east 733 f1df
ecg 2814
ecg_heart 2815
eco 734 ea35
eda 2816
edgesensor_high 735 f005
edgesensor_low 736 f006
edit 43 e3c9
edit_arrow_down 2817
edit_arrow_up 2818
edit_attributes 737 e578
edit_audio 2819
edit_calendar 738 e742
edit_document 739 f88c
edit_line 2820
edit_location 740 e568
edit_location_alt 741 e1c5
edit_note 742 e745
edit_notifications 743 e525
edit_off 744 e950
edit_road 745 ef4d
edit_square 746 f88d
editor_choice 2821
egg 747 eacc
egg_alt 748 eac8
eject 749 e8fb
elderly 750 f21a
elderly_woman 751 eb69
electric_bike 752 eb1b
electric_bolt 753 ec1c
electric_car 754 eb1c
electric_meter 755 ec1b
electric_moped 756 eb1d
electric_rickshaw 757 eb1e
electric_scooter 758 eb1f
electrical_services 759 f102
elevation 2822
elevator 760 f1a0
email 761 e0be
emergency 762 e1eb
emergency_heat 2823
emergency_heat_2 2824
emergency_home 2825
emergency_recording 763 ebf4
emergency_share 764 ebf6
emergency_share_off 2826
emoji_emotions 765 ea22
emoji_events 766 ea23
emoji_flags 767 ea1a
emoji_food_beverage 768 ea1b
emoji_language 2827
emoji_nature 769 ea1c
emoji_objects 770 ea24
emoji_people 771 ea1d
emoji_symbols 772 ea1e
emoji_transportation 773 ea1f
emoticon 2828
empty_dashboard 2829
enable 2830
encrypted 2831
encrypted_add 2832
encrypted_add_circle 2833
encrypted_minus_circle 2834
encrypted_off 2835
endocrinology 2836
energy 2837
energy_program_saving 2838
energy_program_time_used 2839
energy_savings_leaf 774 ec1a
engineering 775 ea3d
enhance_photo_translate 467 e8fc
enhanced_encryption 776 e63f
ent 2840
enterprise 2841
enterprise_off 2842
equal 2843
equalizer 777 e01d
eraser_size_1 2844
eraser_size_2 2845
eraser_size_3 2846
eraser_size_4 2847
eraser_size_5 2848
error 44 e000
error_circle_rounded 2849
error_med 2850
error_outline 778 e001
escalator 779 f1a1
escalator_warning 780 f1ac
euro 781 ea15
euro_symbol 782 e926
ev_charger 2851
ev_mobiledata_badge 2852
ev_shadow 2853
ev_shadow_add 2854
ev_shadow_minus 2855
ev_station 783 e56d
event 45 e878
event_available 784 e614
event_busy 785 e615
event_list 2856
event_note 786 e616
event_repeat 787 eb7b
event_seat 788 e903
event_upcoming 2857
exclamation 2858
exercise 2859
exit_to_app 789 e879
expand 790 e94f
expand_all 2860
expand_circle_down 791 e7cd
expand_circle_right 2861
expand_circle_up 2862
expand_content 2863
expand_less 46 e5ce
expand_more 47 e5cf
expansion_panels 2864
expension_panels 2864
experiment 2865
explicit 792 e01e
explore 48 e87a
explore_nearby 2866
explore_off 793 e9a8
explosion 2867
export_notes 2868
exposure 794 e3ca
exposure_minus_1 795 e3cb
exposure_minus_2 796 e3cc
exposure_neg_1 795 e3cb
exposure_neg_2 796 e3cc
exposure_plus_1 797 e3cd
exposure_plus_2 798 e3ce
exposure_zero 799 e3cf
extension 800 e87b
extension_off 801 e4f5
eye_tracking 2869
eyebrow 2870
eyeglasses 2871
eyeglasses_2 2872
eyeglasses_2_sound 2873
eyeglasses_3 2874
face 802 e87c
face_2 803 f8da
face_3 804 f8db
face_4 805 f8dc
face_5 806 f8dd
face_6 807 f8de
face_down 2875
face_left 2876
face_nod 2877
face_retouching_natural 808 ef4e
face_retouching_off 809 f007
face_right 2878
face_shake 2879
face_unlock 2880
face_up 2881
facebook 810 f234
fact_check 811 f0c5
factory 812 ebbc
falling 2882
familiar_face_and_zone 2883
family_group 2884
family_history 2885
family_home 2886
family_link 2887
family_restroom 813 f1a2
family_star 2888
fan_focus 2889
fan_indirect 2890
farsight_digital 2891
fast_forward 49 e01f
fast_rewind 50 e020
fastfood 814 e57a
faucet 2892
favorite 51 e87d
favorite_border 815 e87e
favorite_outline 815 e87e
fax 816 ead8
feature_search 2893
featured_play_list 817 e06d
featured_seasonal_and_gifts 2894
featured_video 818 e06e
feed 819 f009
feedback 820 e87f
female 821 e590
femur 2895
femur_alt 2896
fence 822 f1f6
fertile 2897
festival 823 ea68
fiber_dvr 824 e05d
fiber_manual_record 825 e061
fiber_new 826 e05e
fiber_pin 827 e06a
fiber_smart_record 828 e062
file_copy 829 e173
file_copy_off 2898
file_download 830 e2c4
file_download_done 831 e9aa
file_download_off 832 e4fe
file_export 2899
file_json 2900
file_map 2901
file_map_stack 2902
file_open 833 eaf3
file_png 2903
file_present 834 ea0e
file_save 2904
file_save_off 2905
file_upload 835 e2c6
file_upload_off 836 f886
files 2906
filter 837 e3d3
filter_1 838 e3d0
filter_2 839 e3d1
filter_3 840 e3d2
filter_4 841 e3d4
filter_5 842 e3d5
filter_6 843 e3d6
filter_7 844 e3d7
filter_8 845 e3d8
filter_9 846 e3d9
filter_9_plus 847 e3da
filter_alt 848 ef4f
filter_alt_off 849 eb32
filter_arrow_right 2907
filter_b_and_w 850 e3db
filter_cancel 2908
filter_center_focus 851 e3dc
filter_drama 852 e3dd
filter_frames 853 e3de
filter_hdr 854 e3df
filter_list 52 e152
filter_list_alt 855 e94e
filter_list_off 856 eb57
filter_none 857 e3e0
filter_plus 2909
filter_retrolux 2910
filter_tilt_shift 858 e3e2
filter_vintage 859 e3e3
finance 2911
finance_chip 2912
finance_mode 2913
find_in_page 860 e880
find_replace 861 e881
fingerprint 862 e90d
fingerprint_off 2914
fire_check 2915
fire_extinguisher 863 f1d8
fire_hydrant 864 f1a3
fire_hydrant_alt 865 f8f1
fire_truck 866 f8f2
fireplace 867 ea43
first_page 868 e5dc
fit_page 2916
fit_page_height 2917
fit_page_width 2918
fit_screen 869 ea10
fit_width 2919
fitbit 870 e82b
fitness_center 871 eb43
fitness_tracker 2920
fitness_trackers 2921
flag 53 e153
flag_2 2922
flag_check 2923
flag_circle 872 eaf8
flag_filled 2924
flaky 873 ef50
flare 874 e3e4
flash_auto 875 e3e5
flash_off 876 e3e6
flash_on 877 e3e7
flashlight_off 878 f00a
flashlight_on 879 f00b
flatware 880 f00c
flex_direction 2925
flex_no_wrap 2926
flex_wrap 2927
flight 881 e539
flight_class 882 e7cb
flight_land 883 e904
flight_takeoff 884 e905
flights_and_hotels 2928
flightsmode 2929
flip 885 e3e8
flip_camera_android 886 ea37
flip_camera_ios 887 ea38
flip_to_back 888 e882
flip_to_front 889 e883
float_landscape_2 2930
float_portrait_2 2931
flood 890 ebe6
floor 2932
floor_lamp 2933
flourescent 891 f00d
flowchart 2934
flowsheet 2935
fluid 2936
fluid_balance 2937
fluid_med 2938
fluorescent 892 ec31
flutter 2939
flutter_dash 893 e00b
flyover 2940
fmd_bad 894 f00e
fmd_good 895 f00f
foggy 896 e818
folded_hands 2941
folder 54 e2c7
folder_check 2942
folder_check_2 2943
folder_code 2944
folder_copy 897 ebbd
folder_data 2945
folder_delete 898 eb34
folder_eye 2946
folder_info 2947
folder_limited 2948
folder_managed 2949
folder_match 2950
folder_off 899 eb83
folder_open 900 e2c8
folder_shared 901 e2c9
folder_special 902 e617
folder_supervised 2951
folder_zip 903 eb2c
follow_the_signs 904 f222
font_download 905 e167
font_download_off 906 e4f9
food_bank 907 f1f2
foot_bones 2952
footprint 2953
for_you 2954
forest 908 ea99
fork_chart 2955
fork_left 909 eba0
fork_right 910 ebac
fork_spoon 2956
forklift 911 f868
format_align_center 912 e234
format_align_justify 913 e235
format_align_left 914 e236
format_align_right 915 e237
format_bold 916 e238
format_clear 917 e239
format_color_fill 918 e23a
format_color_reset 919 e23b
format_color_text 920 e23c
format_h1 2957
format_h2 2958
format_h3 2959
format_h4 2960
format_h5 2961
format_h6 2962
format_image_back 2963
format_image_break_left 2964
format_image_break_right 2965
format_image_front 2966
format_image_inline_left 2967
format_image_inline_right 2968
format_image_left 2969
format_image_right 2970
format_indent_decrease 921 e23d
format_indent_increase 922 e23e
format_ink_highlighter 2971
format_italic 923 e23f
format_letter_spacing 2972
format_letter_spacing_2 2973
format_letter_spacing_standard 2974
format_letter_spacing_wide 2975
format_letter_spacing_wider 2976
format_line_spacing 924 e240
format_list_bulleted 925 e241
format_list_bulleted_add 926 f849
format_list_numbered 927 e242
format_list_numbered_rtl 928 e267
format_overline 929 eb65
format_paint 930 e243
format_paint_off 2977
format_paragraph 2978
format_quote 931 e244
format_quote_off 2979
format_shapes 932 e25e
format_size 933 e245
format_strikethrough 934 e246
format_text_clip 2980
format_text_overflow 2981
format_text_wrap 2982
format_textdirection_l_to_r 935 e247
format_textdirection_r_to_l 936 e248
format_textdirection_vertical 2983
format_underline 937 e249
format_underlined 937 e249
format_underlined_squiggle 2984
forms_add_on 2985
forms_apps_script 2986
fort 938 eaad
forum 939 e0bf
forward 940 e154
forward_10 941 e056
forward_30 942 e057
forward_5 943 e058
forward_circle 2987
forward_media 2988
forward_to_inbox 944 f187
foundation 945 f200
fragrance 2989
frame_bug 2990
frame_exclamation 2991
frame_inspect 2992
frame_person 2993
frame_person_mic 2994
frame_person_off 2995
frame_reload 2996
frame_source 2997
free_breakfast 946 eb44
free_cancellation 947 e748
front_hand 948 e769
front_loader 949 f869
full_coverage 2998
full_hd 2999
full_stacked_bar_chart 3000
fullscreen 55 e5d0
fullscreen_exit 56 e5d1
fullscreen_portrait 3001
function 3002
function_search 3003
functions 950 e24a
funicular 3004
g_mobiledata 951 f010
g_mobiledata_badge 3005
g_translate 952 e927
gallery_thumbnail 3006
game_bumper_left 3007
game_bumper_right 3008
game_button_l 3009
game_button_l1 3010
game_button_l2 3011
game_button_r 3012
game_button_r1 3013
game_button_r2 3014
game_button_zl 3015
game_button_zr 3016
game_stick_l3 3017
game_stick_left 3018
game_stick_r3 3019
game_stick_right 3020
game_trigger_left 3021
game_trigger_right 3022
gamepad 953 e30f
gamepad_circle_down 3023
gamepad_circle_left 3024
gamepad_circle_right 3025
gamepad_circle_up 3026
gamepad_down 3027
gamepad_left 3028
gamepad_right 3029
gamepad_up 3030
games 954 e021
garage 955 f011
garage_check 3031
garage_door 3032
garage_door_open 3033
garage_home 3034
garage_money 3035
garden_cart 3036
gas_meter 956 ec19
gastroenterology 3037
gate 3038
gavel 957 e90e
general_device 3039
generating_tokens 958 e749
genetics 3040
genres 3041
gesture 959 e155
gesture_select 3042
get_app 960 e884
gif 961 e908
gif_2 3043
gif_box 962 e7a3
girl 963 eb68
gite 964 e58b
glass_cup 3044
globe 3045
globe_2_cancel 3046
globe_2_question 3047
globe_asia 3048
globe_book 3049
globe_clock 3050
globe_location_pin 3051
globe_uk 3052
glucose 3053
glyphs 3054
go_to_line 3055
goat 965 10fffd
golf_course 966 eb45
gondola_lift 3056
google_home_devices 3057
google_plus_reshare 3058
google_tv_remote 3059
google_wifi 3060
gpp_bad 967 f012
gpp_good 968 f013
gpp_maybe 969 f014
gps_fixed 970 e1b3
gps_not_fixed 971 e1b4
gps_off 972 e1b5
grade 973 e885
gradient 974 e3e9
grading 975 ea4f
grain 976 e3ea
graph_1 3061
graph_2 3062
graph_3 3063
graph_4 3064
graph_5 3065
graph_6 3066
graph_7 3067
graph_8 3068
graphic_eq 977 e1b8
graphic_eq_off 3069
grass 978 f205
grid_3x3 979 f015
grid_3x3_off 3070
grid_4x4 980 f016
grid_goldenratio 981 f017
grid_guides 3071
grid_layout_side 3072
grid_off 982 e3eb
grid_on 983 e3ec
grid_view 57 e9b0
grocery 3073
group 58 e7ef
group_add 984 e7f0
group_eye 3074
group_off 985 e747
group_remove 986 e7ad
group_search 3075
group_work 987 e886
grouped_bar_chart 3076
groups 59 f233
groups_2 988 f8df
groups_3 989 f8e0
guardian 3077
gynecology 3078
h_mobiledata 990 f018
h_mobiledata_badge 3079
h_plus_mobiledata 991 f019
h_plus_mobiledata_badge 3080
hail 992 e9b1
hallway 3081
hanami_dango 3082
hand_bones 3083
hand_gesture 3084
hand_gesture_off 3085
hand_meal 3086
hand_package 3087
handheld_controller 3088
handshake 993 ebcb
handwriting_recognition 3089
handyman 994 f10b
hangout_video 3090
hangout_video_off 3091
hard_disk 3092
hard_drive 3093
hard_drive_2 3094
hardware 995 ea59
hd 996 e052
hdr_auto 997 f01a
hdr_auto_select 998 f01b
hdr_enhanced_select 999 ef51
hdr_off 1000 e3ed
hdr_off_select 1001 f01c
hdr_on 1002 e3ee
hdr_on_select 1003 f01d
hdr_plus 1004 f01e
hdr_plus_off 3095
hdr_strong 1005 e3f1
hdr_weak 1006 e3f2
head_mounted_device 3096
headphones 1007 f01f
headphones_battery 1008 f020
headset 1009 e310
headset_mic 1010 e311
headset_off 1011 e33a
healing 1012 e3f3
health_and_beauty 3097
health_and_safety 1013 e1d5
health_cross 3098
health_metrics 3099
heap_snapshot_large 3100
heap_snapshot_multiple 3101
heap_snapshot_thumbnail 3102
hearing 1014 e023
hearing_aid 3103
hearing_aid_disabled 3104
hearing_aid_disabled_left 3105
hearing_aid_left 3106
hearing_disabled 1015 f104
heart_broken 1016 eac2
heart_check 3107
heart_minus 3108
heart_plus 3109
heart_smile 3110
heat 3111
heat_pump 1017 ec18
heat_pump_balance 3112
height 1018 ea16
helicopter 3113
help 1019 e887
help_center 1020 f1c0
help_clinic 3114
help_outline 60 e8fd
hematology 3115
hevc 1021 f021
hexagon 1022 eb39
hide 3116
hide_image 1023 f022
hide_source 1024 f023
high_chair 3117
high_density 3118
high_quality 1025 e024
high_quality_off 3119
high_res 3120
highlight 1026 e25f
highlight_alt 1027 ef52
highlight_keyboard_focus 3121
highlight_mouse_cursor 3122
highlight_off 1028 e888
highlight_remove 1028 e888
highlight_text_cursor 3123
highlighter_size_1 3124
highlighter_size_2 3125
highlighter_size_3 3126
highlighter_size_4 3127
highlighter_size_5 3128
hiking 1029 e50a
history 61 e889
history_2 3129
history_edu 1030 ea3e
history_off 3130
history_toggle_off 1031 f17d
hive 1032 eaa6
hls 1033 eb8a
hls_off 1034 eb8c
holiday_village 1035 e58a
home 62 e88a
home_and_garden 3131
home_app_logo 3132
home_filled 1036 e9b2
home_health 3133
home_improvement_and_tools 3134
home_iot_device 3135
home_max 1037 f024
home_max_dots 3136
home_mini 1038 f025
home_pin 3137
home_repair_service 1039 f100
home_speaker 3138
home_storage 3139
home_storage_gear 3140
home_work 1040 ea09
horizontal_align_center 3141
horizontal_align_left 3142
horizontal_align_right 3143
horizontal_distribute 1041 e014
horizontal_rule 1042 f108
horizontal_split 1043 e947
host 3144
hot_tub 1044 eb46
hotel 1045 e53a
hotel_class 1046 e743
hourglass 3145
hourglass_arrow_down 3146
hourglass_arrow_up 3147
hourglass_bottom 1047 ea5c
hourglass_check 3148
hourglass_disabled 1048 ef53
hourglass_empty 1049 e88b
hourglass_full 1050 e88c
hourglass_pause 3149
hourglass_top 1051 ea5b
house 1052 ea44
house_siding 1053 f202
house_with_shield 3150
houseboat 1054 e584
household_supplies 3151
hov 3152
how_to_reg 1055 e174
how_to_vote 1056 e175
hr_resting 3153
html 1057 eb7e
http 1058 e902
https 1059 e88d
hub 1060 e9f4
humerus 3154
humerus_alt 3155
humidity_high 3156
humidity_indoor 3157
humidity_low 3158
humidity_mid 3159
humidity_percentage 3160
hvac 1061 f10e
hvac_max_defrost 3161
ice_skating 1062 e50b
icecream 1063 ea69
id_card 3162
id_card_2 3163
identity_aware_proxy 3164
identity_platform 3165
ifl 3166
iframe 3167
iframe_off 3168
image 63 e3f4
image_arrow_up 3169
image_aspect_ratio 1064 e3f5
image_inset 3170
image_not_supported 1065 f116
image_search 1066 e43f
imagesearch_roller 1067 e9b4
imagesmode 3171
immunology 3172
import_contacts 1068 e0e0
import_export 1069 e0c3
import_spark 3173
important_devices 1070 e912
in_home_mode 3174
inactive_order 3175
inbox 1071 e156
inbox_customize 3176
inbox_text 3177
inbox_text_asterisk 3178
inbox_text_person 3179
inbox_text_share 3180
incomplete_circle 1072 e79b
indeterminate_check_box 1073 e909
indeterminate_question_box 3181
info 64 e88e
info_i 3182
info_outline 1074 e88f
infrared 3183
ink_eraser 3184
ink_eraser_off 3185
ink_highlighter 3186
ink_highlighter_move 3187
ink_highlighter_off 3188
ink_marker 3189
ink_pen 3190
ink_selection 3191
inpatient 3192
input 1075 e890
input_circle 3193
insert_chart 1076 e24b
insert_chart_filled 3194
insert_chart_outlined 1077 e26a
insert_comment 1078 e24c
insert_drive_file 1079 e24d
insert_emoticon 1080 e24e
insert_invitation 1081 e24f
insert_link 1082 e250
insert_page_break 1083 eaca
insert_photo 1084 e251
insert_text 3195
insights 1085 f092
install_desktop 1086 eb71
install_mobile 1087 eb72
instant_mix 3196
integration_instructions 1088 ef54
interactive_space 3197
interests 1089 e7c8
interpreter_mode 1090 e83b
inventory 1091 e179
inventory_2 1092 e1a1
invert_colors 1093 e891
invert_colors_off 1094 e0c4
invert_colors_on 1093 e891
ios 3198
ios_share 1095 e6b8
iron 1096 e583
iso 1097 e3f6
jamboard_kiosk 3199
japanese_curry 3200
japanese_flag 3201
javascript 1098 eb7c
jewelry 3202
join 3203
join_full 1099 eaeb
join_inner 1100 eaf4
join_left 1101 eaf2
join_right 1102 eaea
joystick 3204
jump_to_element 3205
kanji_alcohol 3206
kayaking 1103 e50c
kebab_dining 1104 e842
keep 3207
keep_off 3208
keep_pin 3207
keep_public 3209
kettle 3210
key 1105 e73c
key_off 1106 eb84
key_vertical 3211
key_visualizer 3212
keyboard 65 e312
keyboard_alt 1107 f028
keyboard_arrow_down 66 e313
keyboard_arrow_left 67 e314
keyboard_arrow_right 68 e315
keyboard_arrow_up 69 e316
keyboard_backspace 1108 e317
keyboard_capslock 1109 e318
keyboard_capslock_badge 3213
keyboard_command 1110 eae0
keyboard_command_key 1111 eae7
keyboard_control 84 e5d3
keyboard_control_key 1112 eae6
keyboard_double_arrow_down 1113 ead0
keyboard_double_arrow_left 1114 eac3
keyboard_double_arrow_right 1115 eac9
keyboard_double_arrow_up 1116 eacf
keyboard_external_input 3214
keyboard_full 3215
keyboard_hide 1117 e31a
keyboard_keys 3216
keyboard_lock 3217
keyboard_lock_off 3218
keyboard_off 3219
keyboard_onscreen 3220
keyboard_option 1118 eadf
keyboard_option_key 1119 eae8
keyboard_previous_language 3221
keyboard_return 1120 e31b
keyboard_tab 1121 e31c
keyboard_tab_rtl 3222
keyboard_voice 1122 e31d
kid_star 3223
king_bed 1123 ea45
kitchen 1124 eb47
kitesurfing 1125 e50d
lab_panel 3224
lab_profile 3225
lab_research 3226
label 1126 e892
label_important 1127 e937
label_important_outline 1128 e948
label_off 1129 e9b6
label_outline 1130 e893
labs 3227
lan 1131 eb2f
landscape 1132 e3f7
landscape_2 3228
landscape_2_edit 3229
landscape_2_off 3230
landslide 1133 ebd7
language 70 e894
language_chinese_array 3231
language_chinese_cangjie 3232
language_chinese_dayi 3233
language_chinese_pinyin 3234
language_chinese_quick 3235
language_chinese_wubi 3236
language_french 3237
language_gb_english 3238
language_international 3239
language_japanese_kana 3240
language_korean_latin 3241
language_pinyin 3242
language_spanish 3243
language_us 3244
language_us_colemak 3245
language_us_dvorak 3246
laps 3247
laptop 1134 e31e
laptop_car 3248
laptop_chromebook 1135 e31f
laptop_mac 1136 e320
laptop_windows 1137 e321
lasso_select 3249
last_page 1138 e5dd
launch 1139 e895
laundry 3250
layers 1140 e53b
layers_clear 1141 e53c
lda 3251
leaderboard 1142 f20c
leak_add 1143 e3f8
leak_remove 1144 e3f9
leave_bags_at_home 1145 f21b
left_click 3252
left_panel_close 3253
left_panel_open 3254
legend_toggle 1146 f11b
lens 1147 e3fa
lens_blur 1148 f029
letter_switch 3255
library_add 1149 e02e
library_add_check 1150 e9b7
library_books 1151 e02f
library_music 1152 e030
license 3256
lift_to_talk 3257
light 1153 f02a
light_group 3258
light_group_2 3259
light_mode 71 e518
light_mode_auto 3260
light_off 3261
lightbulb 1154 e0f0
lightbulb_2 3262
lightbulb_circle 1155 ebfe
lightbulb_outline 1156 e90f
lightning_stand 3263
lightstrip 3264
line_axis 1157 ea9a
line_curve 3265
line_end 3266
line_end_arrow 3267
line_end_arrow_notch 3268
line_end_circle 3269
line_end_diamond 3270
line_end_square 3271
line_start 3272
line_start_arrow 3273
line_start_arrow_notch 3274
line_start_circle 3275
line_start_diamond 3276
line_start_square 3277
line_style 1158 e919
line_weight 1159 e91a
linear_scale 1160 e260
link 72 e157
link_2 3278
link_off 1161 e16f
linked_camera 1162 e438
linked_services 3279
lips 3280
liquor 1163 ea60
list 73 e896
list_2 3281
list_alt 1164 e0ee
list_alt_add 3282
list_alt_check 3283
list_arrow 3284
lists 3285
live_help 1165 e0c6
live_tv 1166 e639
living 1167 f02b
local_activity 1168 e53f
local_airport 1169 e53d
local_atm 1170 e53e
local_attraction 1168 e53f
local_bar 1171 e540
local_cafe 1172 e541
local_car_wash 1173 e542
local_convenience_store 1174 e543
local_dining 1175 e556
local_drink 1176 e544
local_fire_department 1177 ef55
local_florist 1178 e545
local_gas_station 1179 e546
local_grocery_store 1180 e547
local_hospital 1181 e548
local_hotel 1182 e549
local_laundry_service 1183 e54a
local_library 1184 e54b
local_mall 1185 e54c
local_movies 1186 e54d
local_offer 1187 e54e
local_parking 1188 e54f
local_pharmacy 1189 e550
local_phone 1190 e551
local_pizza 1191 e552
local_play 1192 e553
local_police 1193 ef56
local_post_office 1194 e554
local_print_shop 1195 e555
local_printshop 1195 e555
local_restaurant 1175 e556
local_see 1196 e557
local_shipping 1197 e558
local_taxi 1198 e559
location_automation 3286
location_away 3287
location_chip 3288
location_city 1199 e7f1
location_disabled 1200 e1b6
location_history 1201 e55a
location_home 3289
location_off 1202 e0c7
location_on 74 e0c8
location_pin 1203 f1db
location_searching 1204 e1b7
locator_tag 3290
lock 75 e897
lock_clock 1205 ef57
lock_open 76 e898
lock_open_circle 3291
lock_open_right 3292
lock_outline 1206 e899
lock_person 1207 f8f3
lock_reset 1208 eade
login 77 ea77
logo_dev 1209 ead6
logout 78 e9ba
looks 1210 e3fc
looks_3 1211 e3fb
looks_4 1212 e3fd
looks_5 1213 e3fe
looks_6 1214 e3ff
looks_one 1215 e400
looks_two 1216 e401
loop 1217 e028
loupe 1218 e402
low_density 3293
low_priority 1219 e16d
lowercase 3294
loyalty 1220 e89a
lte_mobiledata 1221 f02c
lte_mobiledata_badge 3295
lte_plus_mobiledata 1222 f02d
lte_plus_mobiledata_badge 3296
luggage 1223 f235
lunch_dining 1224 ea61
lyrics 1225 ec0b
macro_auto 3297
macro_off 1226 f8d2
magic_button 3298
magic_exchange 3299
magic_tether 3300
magnification_large 3301
magnification_small 3302
magnify_docked 3303
magnify_fullscreen 3304
mail 79 e158
mail_asterisk 3305
mail_lock 1227 ec0a
mail_off 3306
mail_outline 1228 e0e1
mail_shield 3307
male 1229 e58e
man 1230 e4eb
man_2 1231 f8e1
man_3 1232 f8e2
man_4 1233 f8e3
manage_accounts 1234 f02e
manage_history 1235 ebe7
manage_search 1236 f02f
manga 3308
manufacturing 3309
map 1237 e55b
map_pin_heart 3310
map_pin_review 3311
map_search 3312
maps_home_work 1238 f030
maps_ugc 1239 ef58
margin 1240 e9bb
mark_as_unread 1241 e9bc
mark_chat_read 1242 f18b
mark_chat_unread 1243 f189
mark_email_read 1244 f18c
mark_email_unread 1245 f18a
mark_unread_chat_alt 1246 eb9d
markdown 3313
markdown_convert 3314
markdown_copy 3315
markdown_document 3316
markdown_paste 3317
markdown_spark 3318
markunread 1247 e159
markunread_mailbox 1248 e89b
masked_transitions 3319
masked_transitions_add 3320
masks 1249 f218
massage 3321
match_case 3322
match_case_off 3323
match_word 3324
matter 3325
maximize 1250 e930
meal_dinner 3326
meal_lunch 3327
measuring_tape 3328
media_bluetooth_off 1251 f031
media_bluetooth_on 1252 f032
media_link 3329
media_output 3330
media_output_off 3331
mediation 1253 efa7
medical_information 1254 ebed
medical_mask 3332
medical_services 1255 f109
medication 1256 f033
medication_liquid 1257 ea87
meeting_room 1258 eb4f
memory 1259 e322
memory_alt 3333
menstrual_health 3334
menu 80 e5d2
menu_book 1260 ea19
menu_book_2 3335
menu_open 1261 e9bd
merge 1262 eb98
merge_type 1263 e252
message 1264 e0c9
messenger 504 e0ca
messenger_outline 505 e0cb
metabolism 3336
metro 3337
mfg_nest_yale_lock 3338
mic 81 e029
mic_alert 3339
mic_double 3340
mic_external_off 1265 ef59
mic_external_on 1266 ef5a
mic_gear 3341
mic_none 1267 e02a
mic_off 82 e02b
microbiology 3342
microwave 1268 f204
microwave_gen 3343
military_tech 1269 ea3f
mimo 3344
mimo_disconnect 3345
mindfulness 3346
minimize 83 e931
minor_crash 1270 ebf1
mintmark 3347
miscellaneous_services 1271 f10c
missed_video_call 1272 e073
missed_video_call_filled 3348
missing_controller 3349
mist 3350
mitre 3351
mixture_med 3352
mms 1273 e618
mobile 3353
mobile_2 3354
mobile_3 3355
mobile_alert 3356
mobile_arrow_down 2290
mobile_arrow_right 3357
mobile_arrow_up_right 3358
mobile_block 3359
mobile_camera 3360
mobile_camera_front 3361
mobile_camera_rear 3362
mobile_cancel 3363
mobile_cast 3364
mobile_charge 3365
mobile_chat 3366
mobile_check 3367
mobile_code 3368
mobile_dock 3369
mobile_dots 3370
mobile_friendly 1274 e200
mobile_gear 3371
mobile_hand 3372
mobile_hand_left 3373
mobile_hand_left_off 3374
mobile_hand_off 3375
mobile_info 3376
mobile_landscape 3377
mobile_layout 3378
mobile_lock_landscape 3379
mobile_lock_portrait 3380
mobile_loupe 3381
mobile_menu 3382
mobile_off 1275 e201
mobile_question 3383
mobile_rotate 3384
mobile_rotate_lock 3385
mobile_screen_share 1276 e0e7
mobile_screensaver 3386
mobile_sensor_hi 3387
mobile_sensor_lo 3388
mobile_share 3389
mobile_share_stack 3390
mobile_sound 3391
mobile_sound_2 3392
mobile_sound_off 3393
mobile_speaker 3394
mobile_tap 3395
mobile_text 3396
mobile_text_2 3397
mobile_theft 3398
mobile_ticket 3399
mobile_unlock 3400
mobile_vibrate 3401
mobile_wrench 3402
mobiledata_arrows 3403
mobiledata_off 1277 f034
mode 1278 f097
mode_comment 1279 e253
mode_cool 3404
mode_cool_off 3405
mode_dual 3406
mode_edit 1280 e254
mode_edit_outline 1281 f035
mode_fan 3407
mode_fan_2 3408
mode_fan_off 1282 ec17
mode_heat 3409
mode_heat_cool 3410
mode_heat_off 3411
mode_night 1283 f036
mode_of_travel 1284 e7ce
mode_off_on 3412
mode_standby 1285 f037
model_training 1286 f0cf
modeling 3413
monetization_on 1287 e263
money 1288 e57d
money_bag 3414
money_off 1289 e25c
money_off_csred 1290 f038
money_range 3415
monitor 1291 ef5b
monitor_heart 1292 eaa2
monitor_weight 1293 f039
monitor_weight_gain 3416
monitor_weight_loss 3417
monitoring 3418
monochrome_photos 1294 e403
monorail 3419
mood 1295 e7f2
mood_bad 1296 e7f3
mood_heart 3420
moon_stars 3421
mop 3422
moped 1297 eb28
moped_package 3423
more 1298 e619
more_down 3424
more_horiz 84 e5d3
more_time 1299 ea5d
more_up 3425
more_vert 85 e5d4
mosque 1300 eab2
motion_blur 3426
motion_mode 3427
motion_photos_auto 1301 f03a
motion_photos_off 1302 e9c0
motion_photos_on 1303 e9c1
motion_photos_pause 1304 f227
motion_photos_paused 1305 e9c2
motion_play 3428
motion_sensor_active 3429
motion_sensor_alert 3430
motion_sensor_idle 3431
motion_sensor_urgent 3432
motorcycle 1306 e91b
mountain_flag 3433
mountain_steam 3434
mouse 1307 e323
mouse_lock 3435
mouse_lock_off 3436
move 3437
move_down 1308 eb61
move_group 3438
move_item 3439
move_location 3440
move_selection_down 3441
move_selection_left 3442
move_selection_right 3443
move_selection_up 3444
move_to_inbox 1309 e168
move_up 1310 eb64
moved_location 3445
movie 1311 e02c
movie_creation 1312 e404
movie_edit 1313 f840
movie_edit_off 3446
movie_filter 1314 e43a
movie_info 3447
movie_off 3448
movie_speaker 3449
moving 1315 e501
moving_beds 3450
moving_ministry 3451
mp 1316 e9c3
multicooker 3452
multiline_chart 1317 e6df
multimodal_hand_eye 3453
multiple_airports 3454
multiple_stop 1318 f1b9
multitrack_audio 977 e1b8
museum 1319 ea36
music_cast 3455
music_history 3456
music_note 1320 e405
music_note_2 3457
music_note_add 3458
music_off 1321 e440
music_video 1322 e063
my_library_add 1149 e02e
my_library_books 1151 e02f
my_library_music 1152 e030
my_location 1323 e55c
mystery 3459
nat 1324 ef5c
nature 1325 e406
nature_people 1326 e407
navigate_before 1327 e408
navigate_next 1328 e409
navigation 1329 e55d
near_me 1330 e569
near_me_disabled 1331 f1ef
nearby 3460
nearby_error 1332 f03b
nearby_off 1333 f03c
nephrology 3461
nest_audio 3462
nest_cam_floodlight 3463
nest_cam_indoor 3464
nest_cam_iq 3465
nest_cam_iq_outdoor 3466
nest_cam_magnet_mount 3467
nest_cam_outdoor 3468
nest_cam_stand 3469
nest_cam_wall_mount 3470
nest_cam_wired_stand 1334 ec16
nest_clock_farsight_analog 3471
nest_clock_farsight_digital 3472
nest_connect 3473
nest_detect 3474
nest_display 3475
nest_display_max 3476
nest_doorbell_visitor 3477
nest_eco_leaf 3478
nest_farsight_cool 3479
nest_farsight_dual 3480
nest_farsight_eco 3481
nest_farsight_heat 3482
nest_farsight_seasonal 3483
nest_farsight_weather 3484
nest_found_savings 3485
nest_gale_wifi 3060
nest_heat_link_e 3486
nest_heat_link_gen_3 3487
nest_hello_doorbell 3488
nest_locator_tag 3290
nest_mini 3489
nest_multi_room 3490
nest_protect 3491
nest_remote 3059
nest_remote_comfort_sensor 3492
nest_secure_alarm 3493
nest_sunblock 3494
nest_tag 3290
nest_thermostat 3495
nest_thermostat_e_eu 3496
nest_thermostat_gen_3 3497
nest_thermostat_sensor 3498
nest_thermostat_sensor_eu 3499
nest_thermostat_zirconium_eu 3500
nest_true_radiant 3501
nest_wake_on_approach 3502
nest_wake_on_press 3503
nest_wifi_gale 3504
nest_wifi_mistral 3505
nest_wifi_point 3506
nest_wifi_point_vento 3506
nest_wifi_pro 3507
nest_wifi_pro_2 3508
nest_wifi_router 3505
network_cell 1335 e1b9
network_check 1336 e640
network_intel_node 3509
network_intelligence 3510
network_intelligence_history 3511
network_intelligence_update 3512
network_locked 1337 e61a
network_manage 3513
network_node 3514
network_ping 1338 ebca
network_wifi 1339 e1ba
network_wifi_1_bar 1340 ebe4
network_wifi_1_bar_locked 3515
network_wifi_2_bar 1341 ebd6
network_wifi_2_bar_locked 3516
network_wifi_3_bar 1342 ebe1
network_wifi_3_bar_locked 3517
network_wifi_locked 3518
neurology 3519
new_label 1343 e609
new_releases 1344 e031
new_window 3520
news 3521
newsmode 3522
newspaper 1345 eb81
newsstand 3523
next_plan 1346 ef5d
next_week 1347 e16a
nfc 1348 e1bb
nfc_off 3524
night_shelter 1349 f1f1
night_sight_auto 3525
night_sight_auto_off 3526
night_sight_max 3527
nightlife 1350 ea62
nightlight 1351 f03d
nightlight_round 1352 ef5e
nights_stay 1353 ea46
no_accounts 1354 f03e
no_adult_content 1355 f8fe
no_backpack 1356 f237
no_cell 1357 f1a4
no_crash 1358 ebf0
no_drinks 1359 f1a5
no_encryption 1360 e641
no_encryption_gmailerrorred 1361 f03f
no_flash 1362 f1a6
no_food 1363 f1a7
no_luggage 1364 f23b
no_meals 1365 f1d6
no_meals_ouline 1366 f229
no_meeting_room 1367 eb4e
no_photography 1368 f1a8
no_sim 1369 e0cc
no_sound 3528
no_stroller 1370 f1af
no_transfer 1371 f1d5
noise_aware 1372 ebec
noise_control_off 1373 ebf3
noise_control_on 3529
nordic_walking 1374 e50e
north 1375 f1e0
north_east 1376 f1e1
north_west 1377 f1e2
not_accessible 1378 f0fe
not_accessible_forward 3530
not_interested 1379 e033
not_listed_location 1380 e575
not_started 1381 f0d1
note 1382 e06f
note_add 1383 e89c
note_alt 1384 f040
note_stack 3531
note_stack_add 3532
notes 1385 e26c
notification_add 1386 e399
notification_audio 3533
notification_audio_off 3534
notification_important 1387 e004
notification_multiple 3535
notification_settings 3536
notification_sound 3537
notifications 86 e7f4
notifications_active 1388 e7f7
notifications_none 1389 e7f5
notifications_off 1390 e7f6
notifications_on 1388 e7f7
notifications_paused 1391 e7f8
notifications_unread 3538
now_wallpaper 1392 e1bc
now_widgets 135 e1bd
numbers 1393 eac7
nutrition 3539
ods 3540
odt 3541
offline_bolt 1394 e932
offline_pin 1395 e90a
offline_pin_off 3542
offline_share 1396 e9c5
oil_barrel 1397 ec15
okonomiyaki 3543
on_device_training 1398 ebfd
on_hub_device 3544
oncology 3545
ondemand_video 1399 e63a
online_prediction 1400 f0eb
onsen 3546
opacity 1401 e91c
open_in_browser 1402 e89d
open_in_full 87 f1ce
open_in_new 88 e89e
open_in_new_down 3547
open_in_new_off 1403 e4f6
open_in_phone 3357
open_jam 3548
open_run 3549
open_with 1404 e89f
ophthalmology 3550
oral_disease 3551
orbit 3552
order_approve 3553
order_play 3554
orders 3555
orthopedics 3556
other_admission 3557
other_houses 1405 e58c
outbond 1406 f228
outbound 1407 e1ca
outbox 1408 ef5f
outbox_alt 3558
outdoor_garden 3559
outdoor_grill 1409 ea47
outgoing_mail 1410 f0d2
outlet 1411 f1d4
outlined_flag 1412 e16e
outpatient 3560
outpatient_med 3561
output 1413 ebbe
output_circle 3562
oven 3563
oven_gen 3564
overview 3565
overview_key 3566
owl 3567
oxygen_saturation 3568
p2p 3569
pace 3570
pacemaker 3571
package 3572
package_2 3573
padding 1414 e9c8
padel 3574
page_control 3575
page_footer 3576
page_header 3577
page_info 3578
page_menu_ios 3579
pageless 3580
pages 1415 e7f9
pageview 1416 e8a0
paid 1417 f041
palette 89 e40a
pallet 1418 f86a
pan_tool 1419 e925
pan_tool_alt 1420 ebb9
pan_zoom 3581
panorama 1421 e40b
panorama_fish_eye 1422 e40c
panorama_fisheye 1422 e40c
panorama_horizontal 1423 e40d
panorama_horizontal_select 1424 ef60
panorama_photosphere 1425 e9c9
panorama_photosphere_select 1426 e9ca
panorama_vertical 1427 e40e
panorama_vertical_select 1428 ef61
panorama_wide_angle 1429 e40f
panorama_wide_angle_select 1430 ef62
paragliding 1431 e50f
parent_child_dining 3582
park 1432 ea63
parking_meter 3583
parking_sign 3584
parking_valet 3585
partly_cloudy_day 3586
partly_cloudy_night 3587
partner_exchange 3588
partner_heart 3589
partner_reports 3590
party_mode 1433 e7fa
passkey 3591
passport 3592
password 1434 f042
password_2 3593
password_2_off 3594
patient_list 3595
pattern 1435 f043
pause 90 e034
pause_circle 1436 e1a2
pause_circle_filled 1437 e035
pause_circle_outline 1438 e036
pause_presentation 1439 e0ea
payment 1440 e8a1
payment_arrow_down 3596
payment_card 3597
payments 1441 ef63
paypal 1442 ea8d
pedal_bike 1443 eb29
pediatrics 3598
pen_size_1 3599
pen_size_2 3600
pen_size_3 3601
pen_size_4 3602
pen_size_5 3603
pending 1444 ef64
pending_actions 1445 f1bb
pentagon 1446 eb50
people 1447 e7fb
people_alt 1448 ea21
people_outline 1449 e7fc
people_size_decrease 3604
people_size_increase 3605
percent 1450 eb58
percent_discount 3606
performance_max 3607
pergola 3608
perm_camera_mic 1451 e8a2
perm_contact_cal 1452 e8a3
perm_contact_calendar 1452 e8a3
perm_data_setting 1453 e8a4
perm_device_info 1454 e8a5
perm_device_information 1454 e8a5
perm_identity 1455 e8a6
perm_media 1456 e8a7
perm_phone_msg 1457 e8a8
perm_scan_wifi 1458 e8a9
person 91 e7fd
person_2 1459 f8e4
person_3 1460 f8e5
person_4 1461 f8e6
person_add 1462 e7fe
person_add_alt 1463 ea4d
person_add_alt_1 1464 ef65
person_add_disabled 1465 e9cb
person_alert 3609
person_apron 3610
person_book 3611
person_cancel 3612
person_celebrate 3613
person_check 3614
person_edit 3615
person_filled 3616
person_heart 3617
person_off 1466 e510
person_outline 1467 e7ff
person_pin 1201 e55a
person_pin_circle 1468 e56a
person_play 3618
person_raised_hand 3619
person_remove 1469 ef66
person_remove_alt_1 1470 ef67
person_search 1471 f106
person_shield 3620
person_text 3621
personal_bag 3622
personal_bag_off 3623
personal_bag_question 3624
personal_injury 1472 e6da
personal_places 3625
personal_video 1473 e63b
pest_control 1474 f0fa
pest_control_rodent 1475 f0fd
pet_supplies 3626
pets 1476 e91d
phishing 1477 ead7
phone 1478 e0cd
phone_alt 3627
phone_android 1479 e324
phone_bluetooth_speaker 1480 e61b
phone_callback 1481 e649
phone_cancel 3628
phone_disabled 1482 e9cc
phone_enabled 1483 e9cd
phone_forwarded 1484 e61c
phone_in_talk 1485 e61d
phone_iphone 1486 e325
phone_locked 1487 e61e
phone_missed 1488 e61f
phone_paused 1489 e620
phonelink 1490 e326
phonelink_erase 1491 e0db
phonelink_lock 1492 e0dc
phonelink_off 1493 e327
phonelink_ring 1494 e0dd
phonelink_ring_off 3393
phonelink_setup 1495 e0de
photo 1496 e410
photo_album 1497 e411
photo_auto_merge 3629
photo_camera 1498 e412
photo_camera_back 1499 ef68
photo_camera_front 1500 ef69
photo_filter 1501 e43b
photo_frame 3630
photo_library 1502 e413
photo_prints 3631
photo_size_select_actual 1503 e432
photo_size_select_large 1504 e433
photo_size_select_small 1505 e434
php 1506 eb8f
physical_therapy 3632
piano 1507 e521
piano_off 1508 e520
pickleball 3633
picture_as_pdf 1509 e415
picture_in_picture 1510 e8aa
picture_in_picture_alt 1511 e911
picture_in_picture_center 3634
picture_in_picture_large 3635
picture_in_picture_medium 3636
picture_in_picture_mobile 3637
picture_in_picture_off 3638
picture_in_picture_small 3639
pie_chart 1512 e6c4
pie_chart_filled 3640
pie_chart_outline 1513 f044
pie_chart_outlined 1514 e6c5
pill 3641
pill_off 3642
pin 1515 f045
pin_drop 1516 e55e
pin_end 1517 e767
pin_history 3643
pin_invoke 1518 e763
pin_road 3644
pin_road_2 3645
pinboard 3646
pinboard_unread 3647
pinch 1519 eb38
pinch_zoom_in 3648
pinch_zoom_out 3649
pip 3650
pip_exit 3651
pivot_table_chart 1520 e9ce
pix 1521 eaa3
place 1522 e55f
place_item 3652
plagiarism 1523 ea5a
plane_contrails 3653
planet 3654
planner_banner_ad_pt 3655
planner_review 3656
play_arrow 92 e037
play_circle 1524 e1c4
play_circle_fill 1525 e038
play_circle_filled 1525 e038
play_circle_outline 1526 e039
play_disabled 1527 ef6a
play_for_work 1528 e906
play_lesson 1529 f047
play_music 3041
play_pause 3657
play_shapes 3658
playground 3659
playground_2 3660
playing_cards 3661
playlist_add 1530 e03b
playlist_add_check 1531 e065
playlist_add_check_circle 1532 e7e6
playlist_add_circle 1533 e7e5
playlist_play 1534 e05f
playlist_remove 1535 eb80
plug_connect 3662
plumbing 1536 f107
plus_one 1537 e800
podcasts 1538 f048
podiatry 3663
podium 3664
point_of_sale 1539 f17e
point_scan 3665
poker_chip 3666
policy 1540 ea17
policy_alert 3667
poll 1541 e801
polyline 1542 ebbb
polymer 1543 e8ab
pool 1544 eb48
portable_wifi_off 1545 e0ce
portrait 1546 e416
position_bottom_left 3668
position_bottom_right 3669
position_top_right 3670
post 3671
post_add 1547 ea20
potted_plant 3672
power 1548 e63c
power_input 1549 e336
power_off 1550 e646
power_rounded 3673
power_settings_circle 3674
power_settings_new 1551 e8ac
prayer_times 3675
precision_manufacturing 1552 f049
pregnancy 3676
pregnant_woman 1553 e91e
preliminary 3677
prescriptions 3678
present_to_all 1554 e0df
preview 1555 f1c5
preview_off 3679
price_change 1556 f04a
price_check 1557 f04b
print 1558 e8ad
print_add 3680
print_connect 3681
print_disabled 1559 e9cf
print_error 3682
print_lock 3683
priority 3684
priority_high 93 e645
privacy 3685
privacy_tip 1560 f0dc
private_connectivity 1561 e744
problem 3686
procedure 3687
process_chart 3688
production_quantity_limits 1562 e1d1
productivity 3689
progress_activity 3690
prompt_suggestion 3691
propane 1563 ec14
propane_tank 1564 ec13
psychiatry 3692
psychology 1565 ea4a
psychology_alt 1566 f8ea
public 94 e80b
public_off 1567 f1ca
publish 1568 e255
published_with_changes 1569 f232
pulmonology 3693
pulse_alert 3694
punch_clock 1570 eaa8
push_pin 1571 f10d
qr_code 1572 ef6b
qr_code_2 1573 e00a
qr_code_2_add 3695
qr_code_scanner 1574 f206
query_builder 1575 e8ae
query_stats 1576 e4fc
question_answer 1577 e8af
question_exchange 3696
question_mark 1578 eb8b
queue 1579 e03c
queue_music 1580 e03d
queue_play_next 1581 e066
quick_contacts_dialer 558 e0cf
quick_contacts_mail 556 e0d0
quick_phrases 3697
quick_reference 3698
quick_reference_all 3699
quick_reorder 3700
quickreply 1582 ef6c
quiet_time 2620
quiet_time_active 3701
quiz 1583 f04c
quora 1584 ea98
r_mobiledata 1585 f04d
radar 1586 f04e
radio 1587 e03e
radio_button_checked 95 e837
radio_button_off 96 e836
radio_button_on 95 e837
radio_button_partial 3702
radio_button_unchecked 96 e836
radiology 3703
railway_alert 1588 e9d1
railway_alert_2 3704
rainy 3705
rainy_heavy 3706
rainy_light 3707
rainy_snow 3708
ramen_dining 1589 ea64
ramp_left 1590 eb9c
ramp_right 1591 eb96
range_hood 3709
rate_review 1592 e560
rate_review_rtl 3710
raven 3711
raw_off 1593 f04f
raw_on 1594 f050
read_more 1595 ef6d
readiness_score 3712
real_estate_agent 1596 e73a
rear_camera 3713
rebase 3714
rebase_edit 1597 f846
receipt 1598 e8b0
receipt_long 1599 ef6e
receipt_long_off 3715
recent_actors 1600 e03f
recent_patient 3716
recenter 3717
recommend 1601 e9d2
record_voice_over 1602 e91f
rectangle 1603 eb54
rectangle_add 3718
recycling 1604 e760
reddit 1605 eaa0
redeem 1606 e8b1
redo 1607 e15a
reduce_capacity 1608 f21c
refresh 97 e5d5
regular_expression 3719
relax 3720
release_alert 3721
remember_me 1609 f051
reminder 3722
reminders_alt 3722
remote_gen 3723
remove 98 e15b
remove_circle 1610 e15c
remove_circle_outline 1611 e15d
remove_done 1612 e9d3
remove_from_queue 1613 e067
remove_moderator 1614 e9d4
remove_red_eye 1615 e417
remove_road 1616 ebfc
remove_selection 3724
remove_shopping_cart 1617 e928
reopen_window 3725
reorder 99 e8fe
repartition 1618 f8e8
repeat 1619 e040
repeat_on 1620 e9d6
repeat_one 1621 e041
repeat_one_on 1622 e9d7
replace_audio 3726
replace_image 3727
replace_video 3728
replay 1623 e042
replay_10 1624 e059
replay_30 1625 e05a
replay_5 1626 e05b
replay_circle_filled 1627 e9d8
reply 1628 e15e
reply_all 1629 e15f
report 100 e160
report_gmailerrorred 1630 f052
report_off 1631 e170
report_problem 1632 e8b2
request_page 1633 f22c
request_quote 1634 f1b6
reset_brightness 3729
reset_colors 3730
reset_exposure 3731
reset_focus 3732
reset_image 3733
reset_iso 3734
reset_settings 3735
reset_shadow 3736
reset_shutter_speed 3737
reset_tv 1635 e9d9
reset_white_balance 3738
reset_wrench 3739
resize 3740
resize_window 3741
respiratory_rate 3742
responsive_layout 3743
rest_area 3744
restart_alt 1636 f053
restaurant 1637 e56c
restaurant_menu 1638 e561
restore 1639 e8b3
restore_from_trash 1640 e938
restore_page 1641 e929
resume 3745
reviews 1642 f054
rewarded_ads 3746
rheumatology 3747
rib_cage 3748
rice_bowl 1643 f1f5
right_click 3749
right_panel_close 3750
right_panel_open 3751
ring_volume 1644 e0d1
ring_volume_filled 3752
ripples 3753
road 3754
robot 3755
robot_2 3756
rocket 1645 eba5
rocket_launch 1646 eb9b
roller_shades 1647 ec12
roller_shades_closed 1648 ec11
roller_skating 1649 ebcd
roofing 1650 f201
room 1651 e8b4
room_preferences 1652 f1b8
room_service 1653 eb49
rotate_90_degrees_ccw 1654 e418
rotate_90_degrees_cw 1655 eaab
rotate_auto 3757
rotate_left 1656 e419
rotate_right 1657 e41a
roundabout_left 1658 eb99
roundabout_right 1659 eba3
rounded_corner 1660 e920
route 1661 eacd
router 1662 e328
router_off 3758
routine 3759
rowing 1663 e921
rss_feed 1664 e0e5
rsvp 1665 f055
rtt 1666 e9ad
rubric 3760
rule 1667 f1c2
rule_folder 1668 f1c9
rule_settings 3761
run_circle 1669 ef6f
running_with_errors 1670 e51d
rv_hookup 1671 e642
safety_check 1672 ebef
safety_check_off 3762
safety_divider 1673 e1cc
sailing 1674 e502
salinity 3763
sanitizer 1675 f21d
satellite 1676 e562
satellite_alt 1677 eb3a
sauna 3764
save 101 e161
save_alt 1678 e171
save_as 1679 eb60
save_clock 3765
saved_search 1680 ea11
savings 1681 e2eb
scale 1682 eb5f
scan 3766
scan_delete 3767
scanner 1683 e329
scatter_plot 1684 e268
scene 3768
schedule 102 e8b5
schedule_send 1685 ea0a
schema 1686 e4fd
school 1687 e80c
science 1688 ea4b
science_off 3769
scooter 3770
score 1689 e269
scoreboard 1690 ebd0
screen_lock_landscape 1691 e1be
screen_lock_portrait 1692 e1bf
screen_lock_rotation 1693 e1c0
screen_record 3771
screen_rotation 1694 e1c1
screen_rotation_alt 1695 ebee
screen_rotation_up 3772
screen_search_desktop 1696 ef70
screen_share 1697 e0e2
screenshot 1698 f056
screenshot_frame 3773
screenshot_frame_2 3774
screenshot_keyboard 3775
screenshot_monitor 1699 ec08
screenshot_region 3776
screenshot_tablet 3777
script 3778
scrollable_header 3779
scuba_diving 1700 ebce
sd 1701 e9dd
sd_card 1702 e623
sd_card_alert 1703 f057
sd_storage 1704 e1c2
sdk 3780
search 103 e8b6
search_activity 3781
search_check 3782
search_check_2 3783
search_gear 3784
search_hands_free 3785
search_insights 3786
search_off 1705 ea76
seat_cool_left 3787
seat_cool_right 3788
seat_heat_left 3789
seat_heat_right 3790
seat_read 3791
seat_vent_left 3792
seat_vent_right 3793
seat_window 3794
security 1706 e32a
security_key 3795
security_update 1707 f058
security_update_good 1708 f059
security_update_warning 1709 f05a
segment 1710 e94b
select 3796
select_all 1711 e162
select_check_box 3797
select_to_speak 3798
select_window 3799
select_window_2 3800
select_window_off 3801
self_care 3802
self_improvement 1712 ea78
sell 1713 f05b
sell_cloud 3803
send 104 e163
send_and_archive 1714 ea0c
send_money 3804
send_time_extension 1715 eadb
send_to_mobile 1716 f05c
sensor_door 1717 f1b5
sensor_occupied 1718 ec10
sensor_window 1719 f1b4
sensors 1720 e51e
sensors_krx 3805
sensors_krx_off 3806
sensors_off 1721 e51f
sentiment_calm 3807
sentiment_content 3808
sentiment_dissatisfied 1722 e811
sentiment_excited 3809
sentiment_extremely_dissatisfied 3810
sentiment_frustrated 3811
sentiment_neutral 1723 e812
sentiment_sad 3812
sentiment_satisfied 1724 e813
sentiment_satisfied_alt 1725 e0ed
sentiment_stressed 3813
sentiment_very_dissatisfied 1726 e814
sentiment_very_satisfied 1727 e815
sentiment_worried 3814
serif 3815
server_person 3816
service_toolbox 3817
set_meal 1728 f1ea
settings 105 e8b8
settings_accessibility 1729 f05d
settings_account_box 3818
settings_alert 3819
settings_applications 1730 e8b9
settings_b_roll 3820
settings_backup_restore 1731 e8ba
settings_bluetooth 1732 e8bb
settings_brightness 1733 e8bd
settings_cell 1734 e8bc
settings_cinematic_blur 3821
settings_display 1733 e8bd
settings_ethernet 1735 e8be
settings_heart 3822
settings_input_antenna 1736 e8bf
settings_input_component 1737 e8c0
settings_input_composite 1738 e8c1
settings_input_hdmi 1739 e8c2
settings_input_svideo 1740 e8c3
settings_motion_mode 3823
settings_night_sight 3824
settings_overscan 1741 e8c4
settings_panorama 3825
settings_phone 1742 e8c5
settings_photo_camera 3826
settings_power 1743 e8c6
settings_remote 1744 e8c7
settings_screen 3827
settings_seating 3828
settings_slow_motion 3829
settings_suggest 1745 f05e
settings_system_daydream 1746 e1c3
settings_timelapse 3830
settings_video_camera 3831
settings_voice 1747 e8c8
settop_component 3832
severe_cold 1748 ebd3
shades 3833
shades_closed 3834
shadow 3835
shadow_add 3836
shadow_minus 3837
shape_line 1749 f8d3
shape_recognition 3838
shapes 3839
share 106 e80d
share_arrival_time 1750 e524
share_eta 3840
share_location 1751 f05f
share_off 3841
share_reviews 3842
share_windows 3843
shaved_ice 3844
sheets_column_swap 3845
sheets_rtl 3846
shelf_auto_hide 3847
shelf_position 3848
shelves 1752 f86e
shield 107 e9e0
shield_card 3849
shield_lock 3850
shield_locked 3851
shield_moon 1753 eaa9
shield_person 3852
shield_question 3853
shield_radar 3854
shield_toggle 3855
shield_watch 3856
shield_with_heart 3857
shield_with_house 3858
shift 3859
shift_lock 3860
shift_lock_off 3861
shoe_cleats 3862
shop 1754 e8c9
shop_2 1755 e19e
shop_two 1756 e8ca
shopify 1757 ea9d
shopping_bag 1758 f1cc
shopping_bag_speed 3863
shopping_basket 1759 e8cb
shopping_cart 108 e8cc
shopping_cart_checkout 1760 eb88
shopping_cart_off 3864
shoppingmode 3865
short_stay 3866
short_text 1761 e261
shortcut 1762 f060
show_chart 1763 e6e1
shower 1764 f061
shuffle 1765 e043
shuffle_on 1766 e9e1
shutter_speed 1767 e43d
shutter_speed_add 3867
shutter_speed_minus 3868
sick 1768 f220
side_navigation 3869
sign_language 1769 ebe5
sign_language_2 3870
sign_language_off 3871
signal_cellular_0_bar 1770 f0a8
signal_cellular_1_bar 3872
signal_cellular_2_bar 3873
signal_cellular_3_bar 3874
signal_cellular_4_bar 1771 e1c8
signal_cellular_add 3875
signal_cellular_alt 1772 e202
signal_cellular_alt_1_bar 1773 ebdf
signal_cellular_alt_2_bar 1774 ebe3
signal_cellular_alt_off 3876
signal_cellular_connected_no_internet_0_bar 1775 f0ac
signal_cellular_connected_no_internet_4_bar 1776 e1cd
signal_cellular_no_sim 1777 e1ce
signal_cellular_nodata 1778 f062
signal_cellular_null 1779 e1cf
signal_cellular_off 1780 e1d0
signal_cellular_pause 3877
signal_disconnected 3878
signal_wifi_0_bar 1781 f0b0
signal_wifi_4_bar 1782 e1d8
signal_wifi_4_bar_lock 1783 e1d9
signal_wifi_bad 1784 f063
signal_wifi_connected_no_internet_4 1785 f064
signal_wifi_off 1786 e1da
signal_wifi_statusbar_4_bar 1787 f065
signal_wifi_statusbar_connected_no_internet_4 1788 f066
signal_wifi_statusbar_not_connected 3879
signal_wifi_statusbar_null 1789 f067
signature 3880
signpost 1790 eb91
sim_card 1791 e32b
sim_card_alert 1792 e624
sim_card_download 1793 f068
sim_card_lock 3881
simulation 3882
single_arrow 3883
single_bed 1794 ea48
sip 1795 f069
siren 3884
siren_check 3885
siren_open 3886
siren_question 3887
skateboarding 1796 e511
skeleton 3888
skillet 3889
skillet_cooktop 3890
skip_next 109 e044
skip_previous 110 e045
skull 3891
skull_list 3892
slab_serif 3893
sledding 1797 e512
sleep 3894
sleep_score 3895
slide_library 3896
sliders 3897
slideshow 1798 e41b
slow_motion_video 1799 e068
smart_button 1800 f1c1
smart_card_reader 3898
smart_card_reader_off 3899
smart_display 1801 f06a
smart_outlet 3900
smart_screen 1802 f06b
smart_toy 1803 f06c
smartphone 1804 e32c
smartphone_camera 3360
smb_share 3901
smoke_free 1805 eb4a
smoking_rooms 1806 eb4b
sms 1807 e625
sms_failed 1808 e626
snail 3902
snapchat 1809 ea6e
snippet_folder 1810 f1c7
snooze 1811 e046
snowboarding 1812 e513
snowflake 3903
snowing 1813 e80f
snowing_heavy 3904
snowmobile 1814 e503
snowshoeing 1815 e514
soap 1816 f1b2
soba 3905
social_distance 1817 e1cb
social_leaderboard 3906
solar_power 1818 ec0f
solo_dining 3907
sort 111 e164
sort_by_alpha 1819 e053
sos 1820 ebf7
sound_detection_dog_barking 3908
sound_detection_glass_break 3909
sound_detection_loud_sound 3910
sound_sampler 3911
soundbar 3912
soup_kitchen 1821 e7d3
source 1822 f1c4
source_environment 3913
source_notes 3914
south 1823 f1e3
south_america 1824 e7e4
south_east 1825 f1e4
south_west 1826 f1e5
spa 1827 eb4c
space_bar 1828 e256
space_dashboard 1829 e66b
space_dashboard_2 3915
spatial_audio 1830 ebeb
spatial_audio_off 1831 ebe8
spatial_gallery 3916
spatial_speaker 3917
spatial_tracking 1832 ebea
speaker 1833 e32d
speaker_2 3918
speaker_3 3919
speaker_group 1834 e32e
speaker_notes 1835 e8cd
speaker_notes_off 1836 e92a
speaker_phone 1837 e0d2
special_character 3920
specific_gravity 3921
speech_to_text 3922
speech_to_text_2 3923
speed 112 e9e4
speed_0_25 3924
speed_0_2x 3925
speed_0_5 3926
speed_0_5x 3927
speed_0_75 3928
speed_0_7x 3929
speed_1_2 3930
speed_1_25 3931
speed_1_2x 3932
speed_1_5 3933
speed_1_5x 3934
speed_1_75 3935
speed_1_7x 3936
speed_2 3937
speed_2x 3938
speed_3 3939
speed_4 3940
speed_camera 3941
spellcheck 1838 e8ce
split_scene 3942
split_scene_2 3943
split_scene_down 3944
split_scene_left 3945
split_scene_right 3946
split_scene_up 3947
splitscreen 1839 f06d
splitscreen_add 3948
splitscreen_bottom 3949
splitscreen_landscape 3950
splitscreen_landscape_add 3951
splitscreen_left 3952
splitscreen_portrait 3953
splitscreen_right 3954
splitscreen_top 3955
splitscreen_vertical_add 3956
spo2 3957
spoke 1840 e9a7
sports 1841 ea30
sports_and_outdoors 3958
sports_bar 1842 f1f3
sports_baseball 1843 ea51
sports_basketball 1844 ea26
sports_cricket 1845 ea27
sports_esports 113 ea28
sports_football 1846 ea29
sports_golf 1847 ea2a
sports_gymnastics 1848 ebc4
sports_handball 1849 ea33
sports_hockey 1850 ea2b
sports_kabaddi 1851 ea34
sports_martial_arts 1852 eae9
sports_mma 1853 ea2c
sports_motorsports 1854 ea2d
sports_rugby 1855 ea2e
sports_score 1856 f06e
sports_soccer 1857 ea2f
sports_tennis 1858 ea32
sports_volleyball 1859 ea31
sprinkler 3959
sprint 3960
sql 3961
square 1860 eb36
square_circle 3962
square_dot 3963
square_foot 1861 ea49
ssid_chart 1862 eb66
stack 3964
stack_group 3965
stack_hexagon 3966
stack_off 3967
stack_star 3968
stacked_bar_chart 1863 e9e6
stacked_email 3969
stacked_inbox 3970
stacked_line_chart 1864 f22b
stacks 3971
stadia_controller 3972
stadium 1865 eb90
stairs 1866 f1a9
stairs_2 3973
star 114 e838
star_border 1867 e83a
star_border_purple500 1868 f099
star_half 1869 e839
star_outline 1870 f06f
star_purple500 1871 f09a
star_rate 1872 f0ec
star_rate_half 3974
star_shine 3975
stars 1873 e8d0
stars_2 3976
start 1874 e089
stat_0 3977
stat_1 3978
stat_2 3979
stat_3 3980
stat_minus_1 3981
stat_minus_2 3982
stat_minus_3 3983
stay_current_landscape 1875 e0d3
stay_current_portrait 1876 e0d4
stay_primary_landscape 1877 e0d5
stay_primary_portrait 1878 e0d6
steering_wheel_cool 3984
steering_wheel_heat 3985
step 3986
step_into 3987
step_out 3988
step_over 3989
steppers 3990
steps 3991
stethoscope 3992
stethoscope_arrow 3993
stethoscope_check 3994
sticker 3995
sticker_add 3996
sticky_note 3997
sticky_note_2 1879 f1fc
stock_media 3998
stockpot 3999
stop 115 e047
stop_circle 1880 ef71
stop_screen_share 1881 e0e3
storage 1882 e1db
store 1883 e8d1
store_mall_directory 1884 e563
storefront 1885 ea12
storm 1886 f070
straight 1887 eb95
straighten 1888 e41c
strategy 4000
stream 1889 e9e9
stream_apps 3366
streetview 1890 e56e
stress_management 4001
strikethrough_s 1891 e257
stroke_full 4002
stroke_partial 4003
stroller 1892 f1ae
style 1893 e41d
styler 4004
stylus 4005
stylus_brush 4006
stylus_fountain_pen 4007
stylus_highlighter 4008
stylus_laser_pointer 4009
stylus_note 4010
stylus_pen 4011
stylus_pencil 4012
subdirectory_arrow_left 1894 e5d9
subdirectory_arrow_right 1895 e5da
subheader 4013
subject 1896 e8d2
subscript 1897 f111
subscriptions 1898 e064
subtitles 1899 e048
subtitles_gear 4014
subtitles_off 1900 ef72
subway 1901 e56f
subway_walk 4015
subwoofer 4016
summarize 1902 f071
sunny 1903 e81a
sunny_snowing 1904 e819
superscript 1905 f112
supervised_user_circle 1906 e939
supervised_user_circle_off 4017
supervisor_account 1907 e8d3
support 1908 ef73
support_agent 1909 f0e2
surfing 1910 e515
surgical 4018
surround_sound 1911 e049
swap_calls 1912 e0d7
swap_driving_apps 4019
swap_driving_apps_wheel 4020
swap_horiz 116 e8d4
swap_horizontal_circle 1913 e933
swap_vert 117 e8d5
swap_vert_circle 1914 e8d6
swap_vertical_circle 1914 e8d6
sweep 4021
swipe 1915 e9ec
swipe_down 1916 eb53
swipe_down_alt 1917 eb30
swipe_left 1918 eb59
swipe_left_2 4022
swipe_left_alt 1919 eb33
swipe_right 1920 eb52
swipe_right_2 4023
swipe_right_alt 1921 eb56
swipe_up 1922 eb2e
swipe_up_alt 1923 eb35
swipe_vertical 1924 eb51
switch 4024
switch_access 4025
switch_access_2 4026
switch_access_3 4027
switch_access_shortcut 1925 e7e1
switch_access_shortcut_add 1926 e7e2
switch_account 1927 e9ed
switch_camera 1928 e41e
switch_left 1929 f1d1
switch_off 4028
switch_right 1930 f1d2
switch_video 1931 e41f
switches 4029
sword_rose 4030
swords 4031
symptoms 4032
synagogue 1932 eab0
sync 118 e627
sync_alt 1933 ea18
sync_arrow_down 4033
sync_arrow_up 4034
sync_desktop 4035
sync_disabled 1934 e628
sync_lock 1935 eaee
sync_problem 1936 e629
sync_saved_locally 4036
sync_saved_locally_off 4037
syringe 4038
system_security_update 1937 f072
system_security_update_good 1938 f073
system_security_update_warning 1939 f074
system_update 1940 e62a
system_update_alt 1941 e8d7
system_update_tv 1941 e8d7
tab 1942 e8d8
tab_close 4039
tab_close_inactive 4040
tab_close_right 4041
tab_duplicate 4042
tab_group 4043
tab_inactive 4044
tab_move 4045
tab_new_right 4046
tab_recent 4047
tab_search 4048
tab_unselected 1943 e8d9
table 4049
table_bar 1944 ead2
table_chart 1945 e265
table_chart_view 4050
table_convert 4051
table_edit 4052
table_eye 4053
table_lamp 4054
table_large 4055
table_restaurant 1946 eac6
table_rows 1947 f101
table_rows_narrow 4056
table_sign 4057
table_view 1948 f1be
tablet 1949 e32f
tablet_android 1950 e330
tablet_camera 4058
tablet_mac 1951 e331
tabs 4059
tactic 4060
tag 119 e9ef
tag_faces 1952 e420
takeout_dining 1953 ea74
takeout_dining_2 4061
tamper_detection_off 4062
tamper_detection_on 4063
tap_and_play 1954 e62b
tapas 1955 f1e9
target 4064
target_check 4065
task 1956 f075
task_alt 1957 e2e6
tatami_seat 4066
taunt 4067
taxi_alert 1958 ef74
team_dashboard 4068
telegram 1959 ea6b
temp_preferences_custom 4069
temp_preferences_eco 4070
temple_buddhist 1960 eab3
temple_hindu 1961 eaaf
tenancy 4071
terminal 120 eb8e
terminal_2 4072
terminal_add 4073
terrain 1962 e564
text_ad 4074
text_ad_off 4075
text_compare 4076
text_decrease 1963 eadd
text_fields 1964 e262
text_fields_alt 4077
text_format 1965 e165
text_increase 1966 eae2
text_rotate_up 1967 e93a
text_rotate_vertical 1968 e93b
text_rotation_angledown 1969 e93c
text_rotation_angleup 1970 e93d
text_rotation_down 1971 e93e
text_rotation_none 1972 e93f
text_select_end 4078
text_select_jump_to_beginning 4079
text_select_jump_to_end 4080
text_select_move_back_character 4081
text_select_move_back_word 4082
text_select_move_down 4083
text_select_move_forward_character 4084
text_select_move_forward_word 4085
text_select_move_up 4086
text_select_start 4087
text_snippet 1973 f1c6
text_to_speech 4088
text_up 4089
textsms 1974 e0d8
texture 1975 e421
texture_add 4090
texture_minus 4091
theater_comedy 1976 ea66
theaters 1977 e8da
thermometer 4092
thermometer_add 4093
thermometer_alert 4094
thermometer_gain 4095
thermometer_loss 4096
thermometer_minus 4097
thermostat 1978 f076
thermostat_arrow_down 4098
thermostat_arrow_up 4099
thermostat_auto 1979 f077
thermostat_carbon 4100
things_to_do 4101
thread_unread 4102
threat_intelligence 4103
thumb_down 121 e8db
thumb_down_alt 1980 e816
thumb_down_filled 4104
thumb_down_off 4104
thumb_down_off_alt 1981 e9f2
thumb_up 122 e8dc
thumb_up_alt 1982 e817
thumb_up_filled 4105
thumb_up_off 4105
thumb_up_off_alt 1983 e9f3
thumbnail_bar 4106
thumbs_up_double 4107
thumbs_up_down 1984 e8dd
thunderstorm 1985 ebdb
tibia 4108
tibia_alt 4109
tiktok 1986 ea7e
tile_large 4110
tile_medium 4111
tile_small 4112
tilt_arrow_down 4113
tilt_arrow_up 4114
time_auto 4115
time_to_leave 1987 e62c
timelapse 1988 e422
timeline 1989 e922
timer 123 e425
timer_1 4116
timer_10 1990 e423
timer_10_alt_1 4117
timer_10_select 1991 f07a
timer_2 4118
timer_3 1992 e424
timer_3_alt_1 4119
timer_3_select 1993 f07b
timer_5 4120
timer_5_shutter 4121
timer_arrow_down 4122
timer_arrow_up 4123
timer_off 1994 e426
timer_pause 4124
timer_play 4125
tips_and_updates 1995 e79a
tire_repair 1996 ebc8
title 1997 e264
titlecase 4126
toast 4127
toc 1998 e8de
today 1999 e8df
toggle_off 124 e9f5
toggle_on 125 e9f6
token 2000 ea25
toll 2001 e8e0
tonality 2002 e427
tonality_2 4128
toolbar 4129
tools_flat_head 4130
tools_installation_kit 4131
tools_ladder 4132
tools_level 4133
tools_phillips 4134
tools_pliers_wire_stripper 4135
tools_power_drill 4136
tools_wrench 4137
tooltip 4138
tooltip_2 4139
top_panel_close 4140
top_panel_open 4141
topic 2003 f1c8
tornado 2004 e199
total_dissolved_solids 4142
touch_app 126 e913
touch_double 4143
touch_double_2 4144
touch_long 4145
touch_triple 4146
touchpad_mouse 4147
touchpad_mouse_off 4148
tour 2005 ef75
toys 2006 e332
toys_and_games 4149
toys_fan 4150
track_changes 2007 e8e1
trackpad_input 4151
trackpad_input_2 4152
trackpad_input_3 4153
traffic 2008 e565
traffic_jam 4154
trail_length 4155
trail_length_medium 4156
trail_length_short 4157
train 2009 e570
tram 2010 e571
transcribe 2011 f8ec
transfer_within_a_station 2012 e572
transform 2013 e428
transgender 2014 e58d
transit_enterexit 2015 e579
transit_ticket 4158
transition_chop 4159
transition_dissolve 4160
transition_fade 4161
transition_push 4162
transition_slide 4163
translate 2016 e8e2
translate_indic 4164
transportation 4165
travel 2929
travel_explore 2017 e2db
travel_luggage_and_bags 4166
trending_down 2018 e8e3
trending_flat 2019 e8e4
trending_neutral 2019 e8e4
trending_up 2020 e8e5
triangle_circle 4167
trip 4168
trip_origin 2021 e57b
trolley 2022 f86b
trolley_cable_car 4169
trophy 4170
troubleshoot 2023 e1d2
try 2024 f07c
tsunami 2025 ebd8
tsv 4171
tty 2026 f1aa
tune 127 e429
tungsten 2027 f07d
turn_left 2028 eba6
turn_right 2029 ebab
turn_sharp_left 2030 eba7
turn_sharp_right 2031 ebaa
turn_slight_left 2032 eba4
turn_slight_right 2033 eb9a
turned_in 2034 e8e6
turned_in_not 2035 e8e7
tv 2036 e333
tv_displays 4172
tv_gen 4173
tv_guide 4174
tv_next 4175
tv_off 2037 e647
tv_options_edit_channels 4176
tv_options_input_settings 4177
tv_remote 4178
tv_signin 4179
tv_with_assistant 4180
two_pager 4181
two_pager_store 4182
two_wheeler 2038 e9f9
type_specimen 2039 f8f0
u_turn_left 2040 eba1
u_turn_right 2041 eba2
udon 4183
ulna_radius 4184
ulna_radius_alt 4185
umbrella 2042 f1ad
unarchive 2043 e169
undereye 4186
undo 2044 e166
unfold_less 2045 e5d6
unfold_less_double 2046 f8cf
unfold_more 2047 e5d7
unfold_more_double 2048 f8d0
ungroup 4187
universal_currency 4188
universal_currency_alt 4189
universal_local 4190
unknown_2 2664
unknown_5 4191
unknown_7 4089
unknown_document 4192
unknown_med 4193
unlicense 4194
unpaved_road 4195
unpin 3208
unpublished 2049 f236
unsubscribe 2050 e0eb
upcoming 2051 f07e
update 2052 e923
update_disabled 2053 e075
upgrade 2054 f0fb
upi_pay 4196
upload 128 f09b
upload_2 4197
upload_file 2055 e9fc
uppercase 4198
urology 4199
usb 2056 e1e0
usb_off 2057 e4fa
user_attributes 4200
vaccines 2058 e138
vacuum 4201
vacuum_2 4202
vacuum_2_on 4203
valve 4204
vape_free 2059 ebc6
vaping_rooms 2060 ebcf
variable_add 4205
variable_insert 4206
variable_remove 4207
variables 4208
ventilator 4209
verified 129 ef76
verified_off 4210
verified_user 2061 e8e8
vertical_align_bottom 2062 e258
vertical_align_center 2063 e259
vertical_align_top 2064 e25a
vertical_distribute 2065 e076
vertical_shades 2066 ec0e
vertical_shades_closed 2067 ec0d
vertical_split 2068 e949
vibration 2069 e62d
video_call 2070 e070
video_camera_back 2071 f07f
video_camera_back_add 4211
video_camera_front 2072 f080
video_camera_front_off 4212
video_chat 2073 f8a0
video_collection 2074 e04a
video_file 2075 eb87
video_frame_copy 4213
video_frame_save 4214
video_label 2076 e071
video_library 2074 e04a
video_search 4215
video_settings 2077 ea75
video_stable 2078 f081
video_template 4216
videocam 2079 e04b
videocam_alert 4217
videocam_off 2080 e04c
videogame_asset 2081 e338
videogame_asset_off 2082 e500
view_agenda 2083 e8e9
view_apps 4218
view_array 2084 e8ea
view_carousel 2085 e8eb
view_column 2086 e8ec
view_column_2 4219
view_comfortable 2087 e42a
view_comfy 2087 e42a
view_comfy_alt 2088 eb73
view_compact 2089 e42b
view_compact_alt 2090 eb74
view_cozy 2091 eb75
view_day 2092 e8ed
view_headline 2093 e8ee
view_in_ar 2094 e9fe
view_in_ar_new 4220
view_in_ar_off 4221
view_kanban 2095 eb7f
view_list 2096 e8ef
view_module 2097 e8f0
view_object_track 4222
view_quilt 2098 e8f1
view_real_size 4223
view_sidebar 2099 f114
view_stream 2100 e8f2
view_timeline 2101 eb85
view_week 2102 e8f3
vignette 2103 e435
vignette_2 4224
villa 2104 e586
visibility 130 e8f4
visibility_lock 4225
visibility_off 131 e8f5
vital_signs 4226
vitals 4227
vo2_max 4228
voice_chat 2105 e62e
voice_chat_off 4229
voice_over_off 2106 e94a
voice_selection 4230
voice_selection_off 4231
voicemail 2107 e0d9
voicemail_2 4232
volcano 2108 ebda
volume_down 2109 e04d
volume_down_alt 2110 e79c
volume_mute 2111 e04e
volume_off 132 e04f
volume_up 133 e050
volunteer_activism 2112 ea70
voting_chip 4233
vpn_key 2113 e0da
vpn_key_alert 4234
vpn_key_off 2114 eb7a
vpn_lock 2115 e62f
vpn_lock_2 4235
vr180_create2d 4236
vr180_create2d_off 4237
vrpano 2116 f082
walk_bike 4238
wall_art 4239
wall_lamp 4240
wallet 2117 f8ff
wallet_giftcard 481 e8f6
wallet_membership 482 e8f7
wallet_travel 483 e8f8
wallpaper 1392 e1bc
wallpaper_slideshow 4241
wand_shine 4242
wand_stars 4243
ward 4244
warehouse 2118 ebb8
warning 134 e002
warning_amber 2119 f083
warning_off 4245
wash 2120 f1b1
washoku 4246
watch 2121 e334
watch_alert 4247
watch_arrow 4248
watch_arrow_down 4249
watch_button 4250
watch_button_press 4251
watch_check 4252
watch_later 2122 e924
watch_lock 4253
watch_off 2123 eae3
watch_screentime 4254
watch_vibration 4255
watch_wake 4256
water 2124 f084
water_bottle 4257
water_bottle_large 4258
water_damage 2125 f203
water_do 4259
water_drop 2126 e798
water_drops 4260
water_ec 4261
water_full 4262
water_heater 4263
water_lock 4264
water_loss 4265
water_lux 4266
water_medium 4267
water_orp 4268
water_ph 4269
water_pump 4270
water_voc 4271
waterfall_chart 2127 ea00
waves 2128 e176
waving_hand 2129 e766
wb_auto 2130 e42c
wb_cloudy 2131 e42d
wb_incandescent 2132 e42e
wb_iridescent 2133 e436
wb_shade 2134 ea01
wb_sunny 2135 e430
wb_twighlight 2136 ea02
wb_twilight 2137 e1c6
wb_twilight_2 4272
wc 2138 e63d
weather_hail 4273
weather_mix 4274
weather_snowy 4275
web 2139 e051
web_asset 2140 e069
web_asset_off 2141 e4f7
web_stories 2142 e595
web_traffic 4276
webhook 2143 eb92
wechat 2144 ea81
weekend 2145 e16b
weight 4277
west 2146 f1e6
whatshot 2147 e80e
wheat 4278
wheelchair_pickup 2148 f1ab
where_to_vote 2149 e177
widget_medium 4279
widget_menu 4280
widget_small 4281
widget_width 4282
widgets 135 e1bd
width 4283
width_full 2150 f8f5
width_normal 2151 f8f6
width_wide 2152 f8f7
wifi 136 e63e
wifi_1_bar 2153 e4ca
wifi_2_bar 2154 e4d9
wifi_add 4284
wifi_calling 2155 ef77
wifi_calling_1 4285
wifi_calling_2 4286
wifi_calling_3 2156 f085
wifi_calling_bar_1 4287
wifi_calling_bar_2 4288
wifi_calling_bar_3 4289
wifi_channel 2157 eb6a
wifi_device 4290
wifi_find 2158 eb31
wifi_home 4291
wifi_lock 2159 e1e1
wifi_notification 4292
wifi_off 2160 e648
wifi_password 2161 eb6b
wifi_protected_setup 2162 f0fc
wifi_proxy 4293
wifi_tethering 2163 e1e2
wifi_tethering_error 2164 ead9
wifi_tethering_error_rounded 2165 f086
wifi_tethering_off 2166 f087
wind_power 2167 ec0c
window 2168 f088
window_closed 4294
window_open 4295
window_sensor 4296
windshield_defrost_auto 4297
windshield_defrost_front 4298
windshield_defrost_rear 4299
windshield_heat_front 4300
wine_bar 2169 f1e8
woman 2170 e13e
woman_2 2171 f8e7
woo_commerce 2172 ea6d
wordpress 2173 ea9f
work 2174 e8f9
work_alert 4301
work_history 2175 ec09
work_off 2176 e942
work_outline 2177 e943
work_update 4302
workflow 2314
workspace_premium 2178 e7af
workspaces 2179 e1a0
workspaces_filled 2180 ea0d
workspaces_outline 2181 ea0f
wounds_injuries 4303
wrap_text 2182 e25b
wrist 4304
wrong_location 2183 ef78
wysiwyg 2184 f1c3
x_circle 4305
y_circle 4306
yakitori 4307
yard 2185 f089
yoshoku 4308
your_trips 4309
youtube_activity 4310
youtube_searched_for 2186 e8fa
zone_person_alert 4311
zone_person_idle 4312
zone_person_urgent 4313
zoom_in 137 e8ff
zoom_in_map 2187 eb2d
zoom_out 138 e900
zoom_out_map 2188 e56b
]]

for name, cell, codepoint in string.gmatch(DATA, "([%w_]+) (%d+) ?(%x*)") do
	IconSheet.Index[name] = tonumber(cell)
	if codepoint ~= "" then
		IconSheet.Codepoints[name] = tonumber(codepoint, 16)
	end
end

return IconSheet
