#!/usr/bin/env python3
"""Render every icon in src/Core/Icons.lua into one PNG sprite sheet per style.

Executors reliably load external *images* through getcustomasset (the same
way NeverLose loads its logo), while custom *fonts* built from getcustomasset
files don't work everywhere. So the icons ship as images too: each style is a
grid of white glyphs on transparency (tinted at runtime via ImageColor3),
rendered from the official Material Icons fonts.

Outputs:
  assets/icons/MaterialIcons<Style>.png   one sheet per style
  src/Core/IconSheet.lua                  name -> cell index, grid geometry

Usage: pip install fonttools pillow && python3 tools/build_icon_sheets.py
       (run tools/convert_icon_fonts.py first if assets/fonts is missing)
"""
import io
import math
import re
import urllib.request
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent.parent
ICONS_LUA = ROOT / "src" / "Core" / "Icons.lua"
SHEET_LUA = ROOT / "src" / "Core" / "IconSheet.lua"
OUT = ROOT / "assets" / "icons"

CELL = 64  # px per icon; icons are drawn 24-48px in the UI, so this stays crisp
GUTTER = 4  # transparent margin around each cell so neighbours never bleed in
PITCH = CELL + 2 * GUTTER  # 12 x 72 = 864 px, under Roblox's 1024 px image limit
COLUMNS = 12
FILLED_URL = "https://raw.githubusercontent.com/google/material-design-icons/master/font/MaterialIcons-Regular.ttf"
STYLES = {
    "Filled": FILLED_URL,
    "Outlined": ROOT / "assets" / "fonts" / "MaterialIconsOutlined-Regular.ttf",
    "Round": ROOT / "assets" / "fonts" / "MaterialIconsRound-Regular.ttf",
    "Sharp": ROOT / "assets" / "fonts" / "MaterialIconsSharp-Regular.ttf",
}


def read_codepoints():
    source = ICONS_LUA.read_text(encoding="utf-8")
    block = re.search(r"local CODEPOINTS = \{\n(.*?)\n\}", source, re.S).group(1)
    return sorted((name, int(cp, 16)) for name, cp in re.findall(r"\t(\w+) = (0x[0-9a-f]+),", block))


def load_font(source):
    if isinstance(source, Path):
        return ImageFont.truetype(str(source), CELL)
    with urllib.request.urlopen(source) as response:
        return ImageFont.truetype(io.BytesIO(response.read()), CELL)


def main():
    icons = read_codepoints()
    rows = math.ceil(len(icons) / COLUMNS)
    OUT.mkdir(parents=True, exist_ok=True)

    for style, source in STYLES.items():
        font = load_font(source)
        sheet = Image.new("RGBA", (COLUMNS * PITCH, rows * PITCH), (255, 255, 255, 0))
        draw = ImageDraw.Draw(sheet)
        for index, (_, codepoint) in enumerate(icons):
            x = (index % COLUMNS) * PITCH + GUTTER
            y = (index // COLUMNS) * PITCH + GUTTER
            # Material glyphs span exactly one em from the baseline up
            # (ascent = em, descent = 0), so the baseline sits at the cell bottom.
            draw.text((x, y + CELL), chr(codepoint), font=font, fill=(255, 255, 255, 255), anchor="ls")
        path = OUT / f"MaterialIcons{style}.png"
        sheet.save(path, optimize=True)
        print(f"wrote {path.relative_to(ROOT)} ({sheet.width}x{sheet.height}, {path.stat().st_size // 1024} KB)")

    lines = [
        "-- Generated by tools/build_icon_sheets.py from the CODEPOINTS table in",
        "-- Icons.lua; do not edit by hand. Geometry of the icon sprite sheets in",
        "-- assets/icons/ (one per style) and each icon's cell index (0-based).",
        "return {",
        f"\tCell = {CELL}, -- icon size in px",
        f"\tPitch = {PITCH}, -- distance between cells (cell + gutters)",
        f"\tGutter = {GUTTER},",
        f"\tColumns = {COLUMNS},",
        f"\tRows = {rows},",
        "\tIndex = {",
    ]
    lines += [f"\t\t{name} = {index}," for index, (name, _) in enumerate(icons)]
    lines += ["\t},", "}", ""]
    SHEET_LUA.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {SHEET_LUA.relative_to(ROOT)} ({len(icons)} icons)")


if __name__ == "__main__":
    main()
