#!/usr/bin/env python3
"""Bundle src/ into a single self-contained Luau file.

The modules use Roblox-style relative requires (`require(script.Parent.X)`),
so the bundle rebuilds a tiny virtual `script` tree and passes each module
its own `script` node plus a `require` that resolves those nodes. The result
returns the MD3 table, so it works with `loadstring(source)()` or pasted
into a single ModuleScript.

Usage: python3 tools/bundle.py  ->  writes dist/MaterialDesign3.luau
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
OUT = ROOT / "dist" / "MaterialDesign3.luau"
ROOT_NAME = "MaterialDesign3"

PRELUDE = """\
-- MaterialDesign3 (MD3) bundled build. Generated by tools/bundle.py from src/;
-- do not edit by hand. Returns the MD3 table.
local realRequire = require

local Node = {}
Node.__index = function(self, key)
	local child = rawget(self, "_children")[key]
	if child == nil then
		error(`{tostring(key)} is not a valid member of {rawget(self, "Name")}`, 2)
	end
	return child
end

local function newNode(name, parent)
	local node = setmetatable({ Name = name, Parent = parent, _children = {} }, Node)
	if parent then
		rawget(parent, "_children")[name] = node
	end
	return node
end

local loaders = {}
local cache = {}
local LOADING = {}

local function bundleRequire(target)
	local loader = loaders[target]
	if loader == nil then
		return realRequire(target)
	end
	local cached = cache[target]
	if cached == LOADING then
		error(`Cyclic require of {rawget(target, "Name")}`, 2)
	elseif cached == nil then
		cache[target] = LOADING
		cached = loader(target, bundleRequire)
		cache[target] = cached
	end
	return cached
end
"""


def lua_ident(parts):
    return "N_" + "_".join(parts) if parts else "N_root"


def main():
    lines = [PRELUDE]
    lines.append(f'local N_root = newNode("{ROOT_NAME}", nil)')

    folders = sorted(p for p in SRC.rglob("*") if p.is_dir())
    for folder in folders:
        parts = folder.relative_to(SRC).parts
        parent = lua_ident(parts[:-1])
        lines.append(f'local {lua_ident(parts)} = newNode("{parts[-1]}", {parent})')

    for file in sorted(SRC.rglob("*.lua")):
        rel = file.relative_to(SRC)
        folder_parts = rel.parent.parts
        if file.stem == "init":
            node = lua_ident(folder_parts)
        else:
            node = f'newNode("{file.stem}", {lua_ident(folder_parts)})'
        body = file.read_text(encoding="utf-8").rstrip("\n")
        # Bodies are inserted verbatim (not re-indented) so long strings and
        # comments are byte-for-byte identical to the sources.
        lines.append(f"\n-- {rel.as_posix()}")
        lines.append(f"loaders[{node}] = function(script, require)")
        lines.append(body)
        lines.append("end")

    lines.append("\nreturn bundleRequire(N_root)\n")

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
